### ISSUE TITLE
Dates are prefixed with extra number

### ISSUE THREAD

**Issue by cas--** [andstatus/todoagenda#10]
![sketch-1582672901179](https://user-images.githubusercontent.com/606038/75296626-98dee480-5825-11ea-9ae7-f98054582f3d.png)

**Comment by yvolk** [comment]
This is  "Number of days to event" date format.
In order to change or hide this completely please go to Settings -> Layout -> Entry date format
![Screenshot_2020-02-26-08-21-02-203](https://user-images.githubusercontent.com/207716/75314520-05330580-5871-11ea-820a-76c81f4ea2b6.jpeg)

**Comment by cas--** [comment]
Ah ok thanks! Was this in a recent update? Because it really shouldn't change a user's layout.

Also for me it is actually the day header date format that had a different format than expected.

![Screenshot_20200226-085148](https://user-images.githubusercontent.com/606038/75328324-bcca1680-5875-11ea-9003-4ea80701261f.png)

**Comment by kingmustard** [comment]
I also had this issue and the developer pointed me to this thread 🙂

Changing 'Day header date format' to 'Default with Weekday' fixed it 👍

**Comment by yvolk** [comment]
As you noticed, there is no exactly the same Date Format for a Day header, as before v.4.0: that was a mix of currently present "Default with Number of days to event" with "Default with Weekday" (but not both in any one day!). And this is why I had to choose one of these two during upgrade.
If you want to have both "Number of days to event" and "Weekday" present _in one date_, you can use Custom format, which allows you to create any combination of formats. See and start with "Pattern example"...

Anyway, I think that I will change default value of "Day header date format" to "Default with Weekday" as it looks like more people prefer this.
?!

**Comment by kingmustard** [comment]
> As you noticed, there is no exactly the same Date Format for a Day header, as before v.4.0: that was a mix of currently present "Default with Number of days to event" with "Default with Weekday" (but not both in any one day!). And this is why I had to choose one of these two during upgrade.
> If you want to have both "Number of days to event" and "Weekday" present _in one date_, you can use Custom format, which allows you to create any combination of formats. See and start with "Pattern example"...
> 
> Anyway, I think that I will change default value of "Day header date format" to "Default with Weekday" as it looks like more people prefer this.
> ?!

I think that's a good idea, personally. It wasn't clear that the numbers were a countdown to the event. Also, the fact that the widget headers changed when the app updated may frustrate a lot of people, and only a few (such as myself and cas) would find a way to fix it. You don't want people uninstalling, it benefits no one.

**Comment by yvolk** [comment]
In v.4.0.10 ( see #3 ) I improved the "Default with Number of days to event" Date format.
Now it shows "in N days" and "N days ago" after a date instead of (confusing) numbers without any words. "Yesterday, Today and Tomorrow" are shown before a date, as before.
![Screenshot_1584177427](https://user-images.githubusercontent.com/207716/76679053-4a379580-65ee-11ea-8594-b50ef532ae20.png)
