### ISSUE TITLE
Layout: irritating option

### ISSUE THREAD

**Issue by Spielmops** [andstatus/todoagenda#100]
There's an option in Settings/Layout/Day header that reads: 
"Horizontal line below Day header". 
For me that means, there should be another horizontal line below the header. But what this option really changes is: 
"Day header on top or on bottom of event". 
Imho the option-text should be changed to that. Or the option could be changed to a checkbox-item with text "Day header on bottom of event".

Spielmops

**Comment by yvolk** [comment]
@Spielmops  Looks like the best way to avoid confusion will be changing checkbox to an option "Placement of horizontal line near Day Header" (?) with two clearly defined values:
1. "Horizontal line above Day header" (default)
2. "Horizontal line below Day header"

Regarding "Day header on top or on bottom of event" - this is not what we have now. Day header is always above events of the day.
