### ISSUE TITLE
Not displaying my tasks anymore ?

### ISSUE THREAD

**Issue by Kalytis** [andstatus/todoagenda#101]
I'm using the Tasks app, and for some reason, my ToDo plugin refuses to display my tasks now. They are not recognized as a valid calendar to display.

It's a shame, it was so handful having my tasks in the plugin.

Thanks by advance.

Edit : seemed to be an authorization mess-up with corrections brought under 2.5.5. Uninstalling-reinstalling prompted authorization for Tasks again, and my tasks reappeared.

**Comment by jakobroehrl** [comment]
I have exactly the same problem.
Reinstall solves the problem
OnePlus Nord2

**Comment by gurami000** [comment]
I have, the same problem, reinstalling solves it, but after restarting, the tasks are missing again. Is there any way, other than reinstalling, to prompt the task permission?

**Comment by yvolk** [comment]
> Is there any way, other than reinstalling, to prompt the task permission?

Yes, general Android way for this is to open "Information about ToDo Agenda" app and change to "Deny permission" all tasks permissions.
Next time opening the app Settings you will be prompted to allow tasks permissions.

I just checked that this works on my Android 12 device.

**Comment by Kalytis** [comment]
Denying permission and opening the app's settings doesn't prompt to allow tasks permissions.

Even with a reinstallation, bug appears again after some time.
