### ISSUE TITLE
Contacts Birthdays

### ISSUE THREAD

**Issue by rgdave23** [andstatus/todoagenda#103]
How can I prevent contacts from being used, specifically birthdays.

**Comment by Kalytis** [comment]
Are you sure this setting is related to Todo, which only displays the informations of your calendars, and not to your calendar server ?

**Comment by yvolk** [comment]
Some Calendar apps (Google Calendar, as I think) really publishes contacts' birthdays as calendar events in a dedicated calendar.
This can be prevented by making changes in that calendar app. 
See e.g. this related thread: https://github.com/andstatus/todoagenda/issues/68
