### ISSUE TITLE
Setting to toggle combined dates in header

### ISSUE THREAD

**Issue by SimonDever** [andstatus/todoagenda#11]
I'd like the ability to change the displaying of combined date numbers in headers. At the moment I am shown a list of 2 events that occur on 18 March but which are listed in the widget headers as 16, 18 March without further indication as to if there is an event on 16 or what the dates of the events are themselves.

I'd like to be able to have individual dates listed in the widget header so I can always be sure which date has my events.
![20200302_190805](https://user-images.githubusercontent.com/17378796/75656934-d5d92a00-5cb0-11ea-818d-756c6c5a6520.png)

**Comment by yvolk** [comment]
Hi Simon,
"16" is this case is "Number of days to event", and "18" is a day in a month.
See related https://github.com/andstatus/todoagenda/issues/10

**Comment by SimonDever** [comment]
Thanks for that explanation.
