### ISSUE TITLE
display of unknown calendar entry

### ISSUE THREAD

**Issue by lampyr69** [andstatus/todoagenda#116]
hi,

on today's entry an appointment appeared, which does not belong to any of my calendars. it seems to be some kind of fake.
I checked my calendars, no such appointment.
I clicked on that appointment and got a message like entry doors not exist.

screenshot can be provided, drop me a note

definitively this like to be either a bug or security issue 
Please have look for it.
 
thank you
Alex

**Comment by yvolk** [comment]
Hello Alex. This looks like a bug. But not a bug of our widget.
If you are curious, from which exactly calendar this event is being retrieved by the widget, you can debug this. But this will require some Android programming skills (launching Android Studio, turning on debugging in the widget...)
