### ISSUE TITLE
hide duplicate current date

### ISSUE THREAD

**Issue by citriqa** [andstatus/todoagenda#118]
When no past events are displayed and the widget header is enabled, showing a day header for the current date is redundant, as it can only ever show the date a second time directly beneath the header.
In these cases it should be automatically hidden so as not to use up valuable space and distract from the current day's events.

**Comment by yvolk** [comment]
I don't think that making first date header "implicit" will fit for all users. Especially taking into account that TODAY is usually the most important day and you don't want to confuse it with other days.
If you have too many events for today and think about purpose of each line on a screen, I recommend creating another widget "For today only" and turn off day headers in that widget. Move your old "All days" widget to another page of the screen.
Voila?!

**Comment by citriqa** [comment]
I like having just one widget that I can simply scroll down to see things that are coming up the next couple days; but I can see how it might be a little bit less obvious what the widget is displaying of the current date is special-cased. Maybe it could be an option instead. I'll take a look at how I might implement that once I find some time.
