### ISSUE TITLE
Show WebCal calendar?

### ISSUE THREAD

**Issue by Bondarz** [andstatus/todoagenda#12]
Hi, I have LineageOS 16, calendars via Nextcloud, use Etar and ToDo Agenda.

To synchronize my CalDAV I use DAVx5, for a single .ical calendar ICSx5. All apps from F-Droid.

Within ToDo Agenda I can only display my CalDAV calendars, WebCAL not. Am I doing something wrong?

Thanks

ToDo 3.1.9-565

**Comment by yvolk** [comment]
Hello @Bondarz 
Our widget shows all calendars that are provided by the Android's system service called "Calendar provider" (documented here: https://developer.android.com/guide/topics/providers/calendar-provider )

Simply put, if some "Calendar app" adds (and updates...) its events to this "Calendar provider", then the "ToDo Agenda" (or other calendar widget...) will be able to show it.

I.e. no special support of e.g. "WebCal calendar" is needed from the widget's side. But is is needed from the "WebCal calendar" side.
