### ISSUE TITLE
Can't receive data from own/custom calender, just Android default calendar

### ISSUE THREAD

**Issue by mr-gittes** [andstatus/todoagenda#120]
When uninstalling the default calendar,  todoagenda stops working (no widget displayed)...

Could you please  change this ?

Most people don't want to use the stock cal. app...

**Comment by yvolk** [comment]
The ToDo Agenda does NOT depend on any concrete Calendar app. But it needs Android System's "Calendar Provider" service.
Looks like uninstallation of the default Calendar app at your device broke that service.
This may be specific to your device model...
