### ISSUE TITLE
Feature Request: Add option to filter events "in" as well as "out"

### ISSUE THREAD

**Issue by antonyslater** [andstatus/todoagenda#122]
Would be great if I could select a calendar and only show events with certain text included as well as the current filter removing events based on text content.

We use a shared family calendar and each family member starts their events with their initials, (ie "TS - Doctors") I'd like to create a view for each person by only showing events that start with their specific initials.

**Comment by yvolk** [comment]
So adding new option "Show based on keywords in a title"

**Comment by yvolk** [comment]
@antonyslater I published the updated v.4.7.1. here: #3

**Comment by antonyslater** [comment]
> @antonyslater I published the updated v.4.7.1. here: #3

That is great news, however I am unable to install the published version as my installer keeps on failing when I try to install anything not from the play store... might have to wait for it to hit the beta track. But thank you for implementing my suggestion. :-)
