### ISSUE TITLE
Feature request: Display late tasks before "today"

### ISSUE THREAD

**Issue by MartyLake** [andstatus/todoagenda#125]
Hello,
Thanks for your app, very useful.
Could it be possible to display tasks too? For example, I had planned some tasks for yesterday and went to bed, and now they are not displayed anymore.

Best,

**Comment by yvolk** [comment]
"ToDo Agenda" can show past events ended some hours or days ago. See Settings -> Event Filters -> Past events -> Show past events
Do you mean that this works for Calendar events but not for tasks?

**Comment by MartyLake** [comment]
>  Do you mean that this works for Calendar events but not for tasks?

Yes

**Comment by yvolk** [comment]
Hi Marty, please "Share **events and settings** for debugging" as described in https://github.com/andstatus/todoagenda/issues/71 in order for me to understand, why filtering doesn't work.

**Comment by yvolk** [comment]
No reply...

**Comment by MartyLake** [comment]
Sorry for no reply.
It eventually fixed itself. I am not sure why it wasn't working to begin with.
