### ISSUE TITLE
Last Google Play update almost two years old

### ISSUE THREAD

**Issue by rassie** [andstatus/todoagenda#129]
The app version available at https://play.google.com/store/apps/details?id=org.andstatus.todoagenda is 4.5.5 from March 2022. I assume this has something to do with sanctions, losing access or something along these lines, so maybe not really fixable, but it would at least be nice to see this pointed out in the README.

While we are at it: F-Droid link in the README points to the 2048 game, not Todo Agenda.

**Comment by yvolk** [comment]
Hello @rassie, Thank you for noticing wrong link to F-Droid: I fixed it. BTW, we have v.4.8.0 currently in F-Droid, but it has its own signature, so Google Play hosted version (that was build by myself) cannot be updated via F-Droid.
The latest version that can update Google Play one, is here https://github.com/andstatus/todoagenda/issues/3
And in RuStore also.

Yes, I have problems accessing Google Play store via web. The "access window" :-) opens rarely. And I made several improvements in ToDo Agenda  only recently, so they didn't get there yet. But I will look into updating Google Play also.
