### ISSUE TITLE
Calender list is not being refreshed

### ISSUE THREAD

**Issue by rassie** [andstatus/todoagenda#130]
Having sorted, updated and cleaned up my (Google) calenders for 2024, I noticed that the calender list in the widget settings has not been refreshed and there is no obvious way to refresh them manually. I still see calendars that have been deleted as well as old names for renamed calendars and I don't see any newly created calendars. The calendars are all correctly displayed in Google Calendar app and have been set up correctly for synchronisation.

This is a somewhat creepy bug, since I've tried all of the following:

1. Restart the phone
2. Delete the app (to switch/upgrade to the F-Droid version), re-install and import settings from backup
3. Create a new widget without restoring any settings
4. Delete app, restart the phone, re-install the app, create a new widget (in this order)

From my understanding, some combination of these steps should have triggered a calendar list sync (at the very least, re-installing should have been a clean slate), but it hasn't. Is there some other calendar source than Google's that's being interfaced with?

This all happens on an un-rooted Samsung Galaxy Z Fold5 with all current updates installed.

Any help would be much appreciated.

**Comment by yvolk** [comment]
Hello again @rassie!
Your attempts to fix the outdated (out of sync) calendars supposed that a problem is somewhere in our widget. But it's not :-)
As we found out several times already.
This is why reinstallation of the app doesn't help.

This discussion has several solutions that helped to restore the syncing problem: https://github.com/andstatus/todoagenda/issues/17
