### ISSUE TITLE
Date range: today vs one day

### ISSUE THREAD

**Issue by opk12** [andstatus/todoagenda#132]
Many thanks for this app! About the option for one day, introduced in [4.7.3](https://github.com/andstatus/todoagenda/releases/tag/4.8.0-release), what about `24 h` to distinguish it from today?

**Comment by yvolk** [comment]
Hello @opk12 !
We do have both "Today" and "One day" filter options.
"One day" means "24h". Do you mean that we need to rename "One day" to "24h"?

**Comment by opk12** [comment]
Yes

**Comment by yvolk** [comment]
Done, thank you @opk12 !
Will include in the next release.
