### ISSUE TITLE
Widget is showing D-1 as current day

### ISSUE THREAD

**Issue by oxxm** [andstatus/todoagenda#136]
Hello Team todoagenda,

the widget is showing currently d-1 as current day, 01.04 instead of 02.04. But the content under 01.04 are the entries from 02.04.

Is this related to the home time zone issue in https://github.com/andstatus/todoagenda/issues/135 ?

Using etar version 10 and todoangenda 4.9.0

**Comment by yvolk** [comment]
Yes this could be due to some widget freeze that you noticed.
As I noticed so time ago, the "widget's freeze" is actually some Launcher app failure, because this is a Launcher's code that causes Widgets' redraws and clicks...

**Comment by oxxm** [comment]
thanks for the feedback. I removed the widget and set it up again. It is working now.
