### ISSUE TITLE
New Event Entry layout: truly "All in one row". Now End time is not on a single line

### ISSUE THREAD

**Issue by devolatiles** [andstatus/todoagenda#144]
When I choose to display an event a single line, the endtime is displayed under the starttime, not on a single line.

**Comment by yvolk** [comment]
Hi @devolatiles 
If you prefer not to see **End time**, you can do this turning it off in Settings -> Event details

**Comment by devolatiles** [comment]
Hi @yvolk,

Thanks for the response. I know how to turn the End time off and I did that, because it was not on the same line. But if I choose "everything on a single line" (sorry I don't know the exact words, because I see it in Dutch) at the first entry in Settings, Layout => input event formatting, then the End Time should be on the same line as the Start time I would expect, which is what I would also prefer to have in my widget so I can see more entries including the end time.

PS: The widget is absolutely awesome btw.

**Comment by yvolk** [comment]
@devolatiles I assume that End time is on the second line because it doesn't fit into the first line.
Do you prefer to have it truncated?
Please explain / provide a screenshot, why do you think it's better to see only some part of end time?

**Comment by devolatiles** [comment]
@yvolk I wouldn't want the end time to be truncated, just the appointment itself if it doesn't fit, just like the widget does now.

I've added some screenshots as an example (I've crossed out people's names).

The first picture is what I have now. I don't show the end time, everything is on a single line, but there is room for the end time on every line. So off course I would like it that it would be there.

The second picture shows the end time under the start time, while I choose everything on a single line in the layout.
The third picture shows the time under the title from layout, then the end time is next to the start time.

The obvious reason I personally choose to have everything on a single line is that I can see the most appointments at the same time in the widget. The second picture example (with end time) shows fewer lines than the first en just marginally more than the third, while in the first and third example everything is nicer spaced than in the second.

The fourth picture shows a smaller widget and then the appointment title itself is truncated.

The fifth picture is a different widget app (which is no longer available). This one has the start and end time on the same line. This is basically what I would expect if I choose to have everything on a single line AND show the end time. If the title of the event doesn't fit anymore on the line, then the title would be truncated (just like in example 4).

I've tried my best to clarify and I hope everything is clear but please tell me if you need more clarification.

![pic1](https://github.com/user-attachments/assets/02fb48fd-1601-436f-b356-2d0adb817543)
![pic2](https://github.com/user-attachments/assets/2fd2dda7-9b42-4087-abb4-8e8bc84a17cd)
![pic3](https://github.com/user-attachments/assets/2c2ecaf7-4463-4300-9a25-4a1a1890d846)
![pic4](https://github.com/user-attachments/assets/9aa53ed8-4245-4057-8c44-8ee2a9fe4422)
![pic5](https://github.com/user-attachments/assets/5a3612e5-dfd9-40fd-b1c4-a4f2f8075a87)

**Comment by yvolk** [comment]
Thank you, I see that you actually suggests adding another widget layout...
![image](https://github.com/user-attachments/assets/c0714346-5942-47f4-afc7-02111ff35fe9)

**Comment by yvolk** [comment]
Hello @devolatiles 
I figured out how to achieve what you want and not to add another widget layout:
I decided to use existing "Multiline details" setting to control if time is multiline.
This way you can decide:
  * if you want to have multiline and fixed width time 
  * or single line but without any width constraint,

Will release is soon...
![singleLineTime](https://github.com/user-attachments/assets/cd27aac4-188c-43c3-a3bf-1ca996f3591e)

**Comment by yvolk** [comment]
And of course you can still have single line title (with everything else in this layout)
![singleLineTime-singleTimeTitle](https://github.com/user-attachments/assets/6b972639-1086-4ab8-aafd-eee70db13a51)

**Comment by devolatiles** [comment]
Thanks @yvolk. Looks very good!

**Comment by yvolk** [comment]
Released in https://github.com/andstatus/todoagenda/releases/tag/4.10.2-release
