### ISSUE TITLE
Compact layout: Optionally remove spacing between view items

### ISSUE THREAD

**Issue by yvolk** [andstatus/todoagenda#15]
Sometimes we need to see as much info as possible in a small widget, even of a 1 x 1 size.
The "Compact layout" option (or maybe some better name needed...) will cause removal or minimizing of all spaces between view items.

On spacing methods in Android: https://material.io/design/layout/spacing-methods.html#

**Comment by bobfranklins** [comment]
Thank you for opening this enhancement ticket. Like I said, I love the app, and it works great for me like it is. Here are my original comments [with one added like this]:

I love your app. Gave it 5 stars, signed up for beta. All other calendar widgets are useless for 1x1 widgets. [They're only day/date, no events.]

I love the very small text option. I'd like it better if I could choose size/width options for the event icon / calendar color bar / task icon, or to reduce the space to its sides. As you could see in the attached screenshot, it crowds the text in a 1x1 widget.

It would further give more room for a 1x1 widget's event text if the empty space above and below the day header reduced more when text size was set to very small.

Cropped screenshot of widget on homescreen attached (1x1 with padding removed), info and settings below. I use Nova Launcher (no root).

{
"deviceInfo": {
"versionCode": 29,
"versionRelease": "10",
"versionCodename": "REL",
"buildManufacturer": "Essential Products",
"buildBrand": "essential",
"buildModel": "PH-1"
},
"applicationInfo": {
"versionName": "4.0.11-673",
"versionCode": 673
},
"settings": {
"widgetId": 61,
"widgetHeaderDateFormat": "hidden:",
"widgetInstanceName": "Caution\/Danger",
"activeSources": [
{
"providerType": 1,
"id": 22,
"title": "CAUTION",
"summary": " bobfranklins@gmail.com",
"color": -21178,
"isAvailable": true
}
],
"eventRange": 0,
"eventsEnded": "NONE",
"fillAllDay": false,
"hideBasedOnKeywords": "",
"widgetHeaderBackgroundColor": 0,
"pastEventsBackgroundColor": -1082623956,
"todaysEventsBackgroundColor": -637534208,
"backgroundColor": -2147483648,
"showDaysWithoutEvents": true,
"showDayHeaders": true,
"dayHeaderDateFormat": "custom-01:EEE d",
"horizontalLineBelowDayHeader": false,
"showPastEventsUnderOneHeader": false,
"showPastEventsWithDefaultColor": false,
"showEventIcon": true,
"entryDateFormat": "days:bbbb",
"showEndTime": false,
"showLocation": true,
"dateFormat": "auto",
"lockedTimeZoneId": "",
"snapshotMode": "live_data",
"refreshPeriodMinutes": 250,
"eventEntryLayout": "DEFAULT",
"multiline_title": true,
"multiline_details": true,
"showOnlyClosestInstanceOfRecurringEvent": false,
"hideDuplicates": false,
"taskScheduling": "date_due",
"taskWithoutDates": "end_of_list",
"filterMode": "normal",
"indicateAlerts": false,
"indicateRecurring": false,
"widgetHeaderLayout": "HIDDEN",
"headerTheme": "DARK",
"dayHeaderThemePast": "DARK",
"entryThemePast": "BLACK",
"dayHeaderTheme": "DARK",
"entryTheme": "DARK",
"dayHeaderThemeFuture": "DARK",
"entryThemeFuture": "DARK",
"textSizeScale": "0.6",
"dayHeaderAlignment": "LEFT"
},
"resultsVersion": 3,
"results": [
{
"providerType": 1,
"executedAt": 1585048128264,
"timeZoneId": "America\/Chicago",
"millisOffsetUtcToLocal": -18000000,
"standardMillisOffsetUtcToLocal": -21600000,
"uri": "content:\/\/com.android.calendar\/instances\/when\/1585048128264\/1585112400000",
"projection": [
"calendar_id",
"event_id",
"title",
"begin",
"end",
"allDay",
"eventLocation",
"hasAlarm",
"rrule",
"displayColor",
"calendar_color"
],
"selection": "selfAttendeeStatus!=2 AND (calendar_id = 22 )",
"selectionArgs": [],
"sortOrder": "startDay ASC, allDay DESC, begin ASC ",
"rows": [
{
"allDay": {
"type": 1,
"value": 1
},
"rrule": {
"type": 3,
"value": "FREQ=DAILY;INTERVAL=28;WKST=MO"
},
"event_id": {
"type": 1,
"value": 5535
},
"calendar_id": {
"type": 1,
"value": 22
},
"eventLocation": {
"type": 3,
"value": ""
},
"end": {
"type": 1,
"value": 1585267200000
},
"displayColor": {
"type": 1,
"value": -30596
},
"title": {
"type": 3,
"value": "Caution"
},
"begin": {
"type": 1,
"value": 1583366400000
},
"hasAlarm": {
"type": 1,
"value": 0
},
"calendar_color": {
"type": 1,
"value": -21178
}
}
]
}
]
}

![Screenshot_20200324-060920](https://user-images.githubusercontent.com/62647882/77529852-6b09b180-6e5e-11ea-89f7-f1937212758e.jpg)

**Comment by yvolk** [comment]
@bobfranklins Implemented in v.4.2.1, see #3 
![compact-layout](https://user-images.githubusercontent.com/207716/91689389-b3936c80-eb6c-11ea-9090-c17ab4534d49.png)
