### ISSUE TITLE
Odd "ID" shown before time

### ISSUE THREAD

**Issue by antonyslater** [andstatus/todoagenda#150]
All of my instances of the widget display some sort of ID/reference before the day/time for each appointment.

There does not appear to be any way to switch this off.
![Screenshot_20240923_205730_One UI Home](https://github.com/user-attachments/assets/d89adffd-f8da-4abf-b08d-fbcbf7b0735e)

**Comment by yvolk** [comment]
@antonyslater BTW, in the latest release I made "Entry date format" set to "Hidden" by default to avoid this confusion.
