### ISSUE TITLE
widget buttons frozen

### ISSUE THREAD

**Issue by leminsc8er** [andstatus/todoagenda#153]
Thank your  for this free, clean and customiseable App! It is one of my faorite and usfull foss app! I have searching long time for this clean app. One of the customroms use your widget and i have copyd it.

Soemtimes i must restart or reinstall the app, because the buttons are frozen. Scrolling works.
I use Android 13 (last update) on nokia g20
Battery options: app have full acess. (*Sometimes i must set it manual again)
Inteligen battery: disabled for this app

Pleas help

**Comment by yvolk** [comment]
Hello @leminsc8er Lately on my Pixel I noticed the system option for an app: "Manage app if unused" that may stop notifications, remove permissions from app... The option is on "App permissions" screen.
Maybe your device has anything like this? Turn such options off.

Just yesterday I made an update to the widget for Android 15, maybe it will run better in this respect on your device, please see it at #3

**Comment by yvolk** [comment]
@leminsc8er By the way, when buttons stopped working, do clicks on events still work?

**Comment by yvolk** [comment]
@leminsc8er And another suggestion: it would be interesting to bring this case to Nova Launcher team.
Maybe they could fix this at their side?!
