### ISSUE TITLE
No events refresh

### ISSUE THREAD

**Issue by flat-linex** [andstatus/todoagenda#17]
I've used the app for quite a long time but after recent updates I no longer get calendar events visualized.

I 
exited beta status
uninstalled
rebooted
reinstalled
granted permissions

It seem that older events can be visualized but not new ones.

Phone is Redmi Note 7, global MIUI 11 stable.

What have I overlooked?

**Comment by yvolk** [comment]
The "ToDo Agenda" app queries calendar events from the (one) Android system service called "Calendar provider".
That "Calendar provider" holds (stores) calendar events that different Calendar apps publish (sync, update, save...) to it.

Your report suggests that syncing is broken between your Calendar app and the "Calendar provider" service. This may be due to changes in privacy or data sharing settings after Calendar app or Android system's (device firmware) update.

Two places to look at:
1. In your device please check Android settings -> Accounts -> syncing state of all "calendar" services.


As one of users confirmed:
> I found the problem. In the Settings: Accounts area, not all the syncs were turned on. It looks like as of Android 10, you have a sync for Google Calendar and a sync for Calendar. Not sure what the difference is!!!! But turning both on seemed to help.

2. Revise Calendar's settings in its web interface. E.g. Google Calendar has lots of settings available via Web Interface only.

**Comment by flat-linex** [comment]
Thx, 

somehow it was a sync problem, even if the Google Calendar app was not suffering from it.

**Comment by yvolk** [comment]
@flat-linex Thanks for the feedback! 
It's interesting, did you create new events at your device? And this is why Google calendar had it even without sync?!

**Comment by bushrang3r** [comment]
I think I'm having this issue too.
I'm using Beta 2020-03-28 v.4.0.12
Android 9 custom ROM
I've also been using the app for quite some time, maybe about a year, but this is the first time I've had this issue. I have not done any updates and the sync settings have not changed.

I always have the widget set to show one month into the future and to show dates without events, but for the last 2 weeks, it has only showed until April 6 (it doesn't show any events or empty dates after April 6 on two different widgets for two different calendars)

I have uninstalled the widget, reinstalled, rebooted, tried changing calendars on different widgets but no change.

**Comment by flat-linex** [comment]
Well as yvolk correctly guessed I had created, after spotting the misbehavior, an event on the phone and this is probably the reason GCal was seeing it. Afterwards I went sync-off and re-enabled all syncs, forcing resync and now it seems to be working

**Comment by bushrang3r** [comment]
OK, it seems to be working again. I deleted my local calendar events, reset the calendar app, and re-imported them and now it works. Sorry about that.

**Comment by yvolk** [comment]
As another user reported via Google Play: "Yes it does seem to be a sync issue, but what bugs me (sorry) is that the Google agenda widget never fails to show all events."

As I see the same behavior was observed in https://github.com/andstatus/todoagenda/issues/17#issuecomment-606505938 and yet it was solved by forcing re-syncing (please read discussion after that comment).
This Google Calendar bug may be related to another known synchronization bug (this time - bug of Google Tasks) that causes some task events not showing: https://issuetracker.google.com/issues/132432317

**Comment by yvolk** [comment]
It came to me that we can workaround this sync problem by forcing calendar events resync programmatically as described here: https://stackoverflow.com/questions/37602804/android-calendar-api-how-to-force-sync-for-a-specific-calendar

I will test this...

**Comment by yvolk** [comment]
Another fix for the Google calendar not showing contacts birthdays problem:
https://eu.community.samsung.com/t5/mobile-apps-services/calendar-app-stopped-showing-contacts-birthdays-after-26th-of/td-p/1864212

**Comment by yvolk** [comment]
Another solution reported by a user:
> Clearing the cache and data in the system calendar apps actually worked well. Possible fix for you.
