### ISSUE TITLE
No Day headers for empty days after the last event

### ISSUE THREAD

**Issue by yvolk** [andstatus/todoagenda#20]
As @bushrang3r tentatively reported, the ToDo Agenda app may not calculate properly number of days in the future for its filter. E.g. for a week in the future...

@bushrang3r In order to fully understand each other and being able to compare our findings please:
1. Create new calendar for test events only, so you could easily share them with public.
2. Create another widget on your device and setup it to show this test Calendar.
3. Create events that allow you to reproduce your problem or questions.
4. Now you are ready to share / report your questions.
5. Create a screenshot AND, what's even more important, go to this widget's settings -> Feedback and Backup -> Share events and settings for debugging -> send resulted JSON (text) data via email or copy to clipboard and paste here to GitHub.

**Comment by bushrang3r** [comment]
Sorry about that. Thank you for your patience.
I've completed the steps above and here are the results.
ToDo Agenda Beta 4.0.12-674
Etar calendar - local offline calendar called 'test'

![Screenshot_20200405-082744_Lawnchair_1](https://user-images.githubusercontent.com/5970120/78464231-b440e780-7721-11ea-9669-ff9e338c4a11.png)

`{
  "deviceInfo": {
    "versionCode": 28,
    "versionRelease": "9",
    "versionCodename": "REL",
    "buildManufacturer": "samsung",
    "buildBrand": "samsung",
    "buildModel": "SM-N910F"
  },
  "applicationInfo": {
    "versionName": "4.0.12-674",
    "versionCode": 674
  },
  "settings": {
    "widgetId": 105,
    "widgetHeaderDateFormat": "defaultWeekday:",
    "widgetInstanceName": "Todo Agenda 1",
    "activeSources": [
      {
        "providerType": 1,
        "id": 8,
        "title": "test",
        "summary": "Offline Calendar",
        "color": -15619228,
        "isAvailable": true
      }
    ],
    "eventRange": 30,
    "eventsEnded": "ONE_MONTH",
    "fillAllDay": false,
    "hideBasedOnKeywords": "",
    "widgetHeaderBackgroundColor": 0,
    "pastEventsBackgroundColor": -1082623956,
    "todaysEventsBackgroundColor": -620756993,
    "backgroundColor": -2147483648,
    "showDaysWithoutEvents": true,
    "showDayHeaders": true,
    "dayHeaderDateFormat": "defaultWeekday:",
    "horizontalLineBelowDayHeader": false,
    "showPastEventsUnderOneHeader": true,
    "showPastEventsWithDefaultColor": false,
    "showEventIcon": true,
    "entryDateFormat": "hidden:",
    "showEndTime": false,
    "showLocation": false,
    "dateFormat": "auto",
    "lockedTimeZoneId": "",
    "snapshotMode": "live_data",
    "refreshPeriodMinutes": 10,
    "eventEntryLayout": "ONE_LINE",
    "multiline_title": false,
    "multiline_details": false,
    "showOnlyClosestInstanceOfRecurringEvent": false,
    "hideDuplicates": false,
    "taskScheduling": "date_due",
    "taskWithoutDates": "end_of_list",
    "filterMode": "debug",
    "indicateAlerts": false,
    "indicateRecurring": false,
    "widgetHeaderLayout": "ONE_ROW",
    "headerTheme": "DARK",
    "dayHeaderThemePast": "DARK",
    "entryThemePast": "BLACK",
    "dayHeaderTheme": "LIGHT",
    "entryTheme": "WHITE",
    "dayHeaderThemeFuture": "DARK",
    "entryThemeFuture": "BLACK",
    "textSizeScale": "0.8",
    "dayHeaderAlignment": "LEFT"
  },
  "resultsVersion": 3,
  "results": [
    {
      "providerType": 1,
      "executedAt": 1586042819709,
      "timeZoneId": "Asia\/Tokyo",
      "millisOffsetUtcToLocal": 32400000,
      "standardMillisOffsetUtcToLocal": 32400000,
      "uri": "content:\/\/com.android.calendar\/instances\/when\/0\/95617584000000",
      "projection": [
        "calendar_id",
        "event_id",
        "title",
        "begin",
        "end",
        "allDay",
        "eventLocation",
        "hasAlarm",
        "rrule",
        "displayColor",
        "calendar_color"
      ],
      "selection": "selfAttendeeStatus!=2 AND (calendar_id = 8 )",
      "selectionArgs": [],
      "sortOrder": "startDay ASC, allDay DESC, begin ASC ",
      "rows": [
        {
          "allDay": {
            "type": 1,
            "value": 1
          },
          "event_id": {
            "type": 1,
            "value": 1726
          },
          "calendar_id": {
            "type": 1,
            "value": 8
          },
          "end": {
            "type": 1,
            "value": 1586131200000
          },
          "displayColor": {
            "type": 1,
            "value": -15619228
          },
          "title": {
            "type": 3,
            "value": "Jdjdidd djsksbdhs"
          },
          "begin": {
            "type": 1,
            "value": 1586044800000
          },
          "hasAlarm": {
            "type": 1,
            "value": 0
          },
          "calendar_color": {
            "type": 1,
            "value": -15619228
          }
        },
        {
          "allDay": {
            "type": 1,
            "value": 1
          },
          "event_id": {
            "type": 1,
            "value": 1727
          },
          "calendar_id": {
            "type": 1,
            "value": 8
          },
          "end": {
            "type": 1,
            "value": 1586217600000
          },
          "displayColor": {
            "type": 1,
            "value": -15619228
          },
          "title": {
            "type": 3,
            "value": "Jsisbvapwifbfv"
          },
          "begin": {
            "type": 1,
            "value": 1586131200000
          },
          "hasAlarm": {
            "type": 1,
            "value": 0
          },
          "calendar_color": {
            "type": 1,
            "value": -15619228
          }
        }
      ]
    }
  ]
}`

**Comment by yvolk** [comment]
@bushrang3r I think that now I understand you: You are wondering why the ToDo Agenda doesn't show Day headers for days after the "Jsisbv..." event on April 6 ?!

This is by design :-)
The widget shows Day headers (optionally, if Layout -> "Show days without events" is set) only BETWEEN other dates with events. In your case there are no events to be shown (that fit into filter settings) after April 6, so no headers for further empty days are shown.

The "Show days without events" option allows you to visualize time distance between events.

**Comment by bushrang3r** [comment]
Ooohhh!!! I see now! :+1:  I never realized that it functioned that way because until now, I always had some events coming up in the near future so they always showed in the widget.  Thank for your help as always!! Please feel free to delete this issue if you like.
