### ISSUE TITLE
[Bug?] The calendar icon in the widget header does not open calendar app (This is "Go to today" icon!)

### ISSUE THREAD

**Issue by redhonker66** [andstatus/todoagenda#24]
There are 4 icons at the top: calendar, +, refresh, 3-dots.  I think the calendar icon used to open the calendar app.  But now clicking on it has no effect.  Was my memory wrong?

Version 4.0.13-675

Thanks

**Comment by yvolk** [comment]
@redhonker66 The "Calendar icon" is actually "Go to today" icon :-)
The icon / button is used to scroll a list of event so that today's events are visible.
