### ISSUE TITLE
[feature request] Add event button on each day

### ISSUE THREAD

**Issue by jrumbold** [andstatus/todoagenda#26]
Have a + button on each day header of the widget to create an event on that day.
The Business Calendar 2 widget has this and I found it very useful, however I stopped using Business Calendar 2 because the number of days the widget displays is limited.
I'd be very happy to test this feature if it gets to that stage.

**Comment by yvolk** [comment]
@jrumbold As I see, in order for this feature to be useful, day headers should be shown even for days without events?!
We don't have that option also...
