### ISSUE TITLE
[Feature Request] Pull down to refresh

### ISSUE THREAD

**Issue by garlandkr** [andstatus/todoagenda#27]
It is very difficult to press the refresh icon, it would be nice to refresh by pulling down on the calendar events from the main view.

**Comment by yvolk** [comment]
@garlandkr Do you know any Open Source widget that does "Pull down to refresh" well? If yes I could lookup implementation there.

**Comment by garlandkr** [comment]
After researching, it appears this is not possible with the current widget implementation in Android. It was just an idea, no examples.
