### ISSUE TITLE
Rescheduled event is still showing up on the original date

### ISSUE THREAD

**Issue by SnoopyGum** [andstatus/todoagenda#30]
When an event is rescheduled, it remains on the original date in the widget. When you tap on the event in the widget it'll even show the new date.

**Comment by yvolk** [comment]
There is a problem on your device in syncing between a calendar app that you are using, and the Android system "Calendar provider" service that feeds calendar event to out "ToDo Agenda" app/widget.

Please read solutions in this thread: https://github.com/andstatus/todoagenda/issues/17

**Comment by SnoopyGum** [comment]
I don't think it's a simple sync problem on a device. The exact same issue appears on multiple devices. I've also tried manually forcing a sync in Account Sync, but the problem persists.

**Comment by yvolk** [comment]
Yes, the issue is quite common, I encountered it also. And solved using the provided solution...

**Comment by SnoopyGum** [comment]
I used the provided solution but it did not resolve.

Paul K

**Comment by yvolk** [comment]
@SnoopyGum If in your concrete case syncing failed then you could try to reschedule the event again... but maybe the Calendar app OR your Android device firmware needs upgrade/fix also...

**Comment by SnoopyGum** [comment]
Already tried all that and it didn't work neither.

*Paul K*

**Comment by yvolk** [comment]
@SnoopyGum So I would try to delete old event and create new with a correct schedule.

**Comment by SnoopyGum** [comment]
Already tried that too. Doesn't work.

*Paul K*

**Comment by yvolk** [comment]
What Calendar app are you using, and what is your device android version?

**Comment by SnoopyGum** [comment]
Just plain Google Calendar, 2020.22.4-318232840-release on both my phone
and my tablet. It's the newest available for my devices on Google Play.

*Paul K*

**Comment by yvolk** [comment]
I would suggest to test syncing while creation and changing calendar event via Google Calendar Web interface:
- test if these events and their changes are visible in a Calendar app at your devices;
- test if the same changes are visible via ToDo Agenda widgets on these devices.

**Comment by yvolk** [comment]
@SnoopyGum It came to me that there could be another reason why you may see outdated events (not one, as you reported, but all of them): this concrete widget could have been switched to the Snapshot mode, and now it simply shows you a snapshot of you events at some day in the past.

Please look in the "Other settings" -> "Lock list of events (Snapshot mode)": "Live data from real sources" should be selected there.

**Comment by SnoopyGum** [comment]
No, I'm not using snapshot mode at all.
*Paul K*

**Comment by yvolk** [comment]
@SnoopyGum OK, at my developer's instances I noticed switches to the Snapshot mode that seemed unintended  (maybe that is a bug...). Although I switch manually also, so I'm not sure on that.
