### ISSUE TITLE
Push the latest stable version onto f-droid

### ISSUE THREAD

**Issue by AlexandreBonneau** [andstatus/todoagenda#31]
Hi, the latest version available on f-droid is 3.1.9-565 from 5 months ago.
Would it be possible to push the latest version (version 4.0.8 for instance which includes the features to display tasks based on their due dates!)?

Anyway, thanks for this great app!

**Comment by yvolk** [comment]
@AlexandreBonneau Thank you for noticing, 
I'm doing this for the last 3+ months.
No F-Droid reviewers found time for my merge requests, my latest merge request is here: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7051

Maybe you could help with merge of that request?!

**Comment by AlexandreBonneau** [comment]
Ah bummer!
Unfortunately, I have no write permission to the f-droid repo (nor expertise in android dev).

I hope F-droid does fix the week-long offset that can occur with the build queue.
Anyway, thanks for your app, it's pretty helpful!

**Comment by yvolk** [comment]
Hi @relan , last year you helped us publishing the "ToDo Agenda" app to F-Droid. Could you help us now to update app data in F-Droid in order to automate its releases there (I switched to static version number and name).
Please see the latest merge request that waits for someone, who can merge it: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7051

**Comment by yvolk** [comment]
I created the issue in F-Droid data repository hoping to draw attention to my merge request:
https://gitlab.com/fdroid/fdroiddata/-/issues/2101

You could support it somehow... As I wrote there, I don't even know, how to facilitate this process...

**Comment by yvolk** [comment]
Thanks to @relan my latest merge request is merged.
I decided not to close the issue in F-Droid ( https://gitlab.com/fdroid/fdroiddata/-/issues/2101 ) to discuss/to ensure that next metadata update won't take that long and so many efforts...

**Comment by yvolk** [comment]
Hooray, thanks to all! The latest v.4.1.1 was automatically identified by F-Droid and is already available in F-Droid: https://f-droid.org/en/packages/org.andstatus.todoagenda/
