### ISSUE TITLE
Start Time and Event Text Vertical Position

### ISSUE THREAD

**Issue by oxxm** [andstatus/todoagenda#32]
Hello,

is it posstible to have the option to center both the start time and the event text? In case no end time is displayed. With the current setup they look misalligned.

Screenshot attached.

![event](https://user-images.githubusercontent.com/39620251/87696401-079aeb00-c791-11ea-984b-4743aec1b410.png)

Thanks.

**Comment by yvolk** [comment]
@oxxm Yes, really, thanks for noticing. I will improve "vertical alignment" of the time field.
![Screenshot (Aug 8, 2020 13_32_13)](https://user-images.githubusercontent.com/207716/89707992-faca7b00-d97b-11ea-9d1e-1f1e235e4cb7.png)

**Comment by oxxm** [comment]
thanks for the feedback. One question to your screenshot, does it show the improved "vertical alignment"?

My Screenshot shows the case where only the "start time" is set to be displayed.

**Comment by yvolk** [comment]
@oxxm No, this screenshot is taken before any changes. It shows that the same problem is observed when no time shown at all (for all day events).
In this case: 
1. Values "02-16" and time "14:10 15:10" are place OK.
2. Value "02-24" in the "date" column should be moved down a bit.

Do you agree, is this what you mean?

**Comment by oxxm** [comment]
yes, exactly. In my screenshot there is no date column however. So the vertical allignment should consider this case too.
Thanks for the feedback!

**Comment by yvolk** [comment]
@oxxm I changed vertical alignment, so it looks now this way. Hope you will find it better than before:
1. No end time.
![Vertical-alignment-001](https://user-images.githubusercontent.com/207716/91665929-c15fd800-eb01-11ea-8606-f560e4505d0c.png)
2. End time is shown:
![Screenshot_1598809676](https://user-images.githubusercontent.com/207716/91666023-5d89df00-eb02-11ea-9976-940c195131bb.png)

**Comment by yvolk** [comment]
Released in v.4.2.1, see #3

**Comment by oxxm** [comment]
@yvolk It looks great, thanks for the feedback!
