### ISSUE TITLE
tasks are now at the end below the dates

### ISSUE THREAD

**Issue by n0rrin** [andstatus/todoagenda#33]
Hi. I use todo-widget with kiss launcher that only offers one home screen so it is very important to me.
Today the tasks on the top of the widget disappeared.
They moved to the bottom below the calendar-tasks what does not really makes sense.
Did not found a switch in the settings.
How to move them back to the top?

**Comment by yvolk** [comment]
On tasks ordering and filtering  please read here: https://github.com/andstatus/todoagenda/issues/4
