### ISSUE TITLE
not all calendars available if multiple google accounts exists

### ISSUE THREAD

**Issue by xenolog** [andstatus/todoagenda#38]
If you have multiple google accounts at the same phone (personal and business, for example) only calendars from last are available to use in widget.

![Screenshot_20200801-115218](https://user-images.githubusercontent.com/270112/89098406-ffc58280-d3ef-11ea-9a6a-1e05d31a5552.jpg)

**Comment by xenolog** [comment]
This effect disappear after re-install application

**Comment by yvolk** [comment]
As our widget doesn't remember a list of calendars anywhere (it asks the Android service "Calendar provider" for this), I think that device reboot could help also.
In general, "Troubleshooting after update" section of the ReadMe page should help: https://github.com/andstatus/todoagenda#changelog
