### ISSUE TITLE
Error Message when tapping under the last event

### ISSUE THREAD

**Issue by oxxm** [andstatus/todoagenda#39]
When tapping under the last event (not on it) in the widget, the following message is displayed (See attached screenshot). Is it an issue with the app itself? If not please ignore.

![error](https://user-images.githubusercontent.com/39620251/89898220-9bb97000-dbe0-11ea-852b-071efbbee1b9.PNG)

**Comment by yvolk** [comment]
@oxxm Thanks for reporting, this is an old bug that recently became apparent due to this new error message screen. 
I fixed this in v.4.2. (Publishing it to Beta channel now https://github.com/andstatus/todoagenda/issues/3 ) After a fix the Widget's Settings screen will appear in such case.

**Comment by oxxm** [comment]
thanks for the feedback!
