### ISSUE TITLE
Tasks.org tasks without due date appear as giant list at end of widget

### ISSUE THREAD

**Issue by abers** [andstatus/todoagenda#40]
Unsure if I have an option misconfigured, but all my tasks from Tasks.org that do not have a due date appear as a mega-long list if I scroll to the bottom of the widget. I have the date range set to "one month" so I'm guessing the expected behaviour would be for these tasks to be hidden?

**Comment by yvolk** [comment]
Hi @abers Please see description and examples of tasks filtering and ordering #4 
I would say that you want to set "Tasks without start and due dates" option to "Hide"?!

Or tasks in that "mega-long list" do have start date?

**Comment by abers** [comment]
Thanks for the reply. I have Event filtering set to "one month", task scheduling as "Show tasks under date due", and tasks without start and due dates set to "Hide" - but still have a mega-list of tasks apparently due on Wednesday, 1st January 50000. None of the tasks that appear in this list have a due or start date. If a task has a due date but it is over a month away it does not appear under any date in the widget as expected.

**Comment by yvolk** [comment]
Fixed in v.4.2.0 #3
