### ISSUE TITLE
App Settings screen disappears from Recents list

### ISSUE THREAD

**Issue by JohnVeness** [andstatus/todoagenda#41]
The Todo Agenda settings app disappears from the Android "Recents" list (I think that's what the multitasking screen is called) if you switch away from it. This can be annoying if I'm trying setup Todo Agenda while following some written instructions. I don't know if this in intentional or not..?

**Comment by yvolk** [comment]
@JohnVeness Yes that was intentional. I thought that settings screen may have outdated info or belong to another "ToDo Agenda" widget and thus confuse a User.

I will check if I can safely allow this.
