### ISSUE TITLE
Displaying of tasks with no date (tasks.org beta)

### ISSUE THREAD

**Issue by shompoe** [andstatus/todoagenda#43]
Hi,

Using tasks.org beta all tasks with no set dates are shown under day header "1 January 5000". I have set "Tasks without start and due dates" to "Hidden".

**Comment by yvolk** [comment]
@shompoe Thanks the report. 
Looks like this is the same case as #40. I will try the tasks.org beta app and think, how to fix this. Will follow up in #40.
