### ISSUE TITLE
Text is partially hidden in the "Time below title" layout and the Smallest text size

### ISSUE THREAD

**Issue by yvolk** [andstatus/todoagenda#44]
When I turn on "Show layout bounds" in Android "Developer options" I see that a view containing time and location doesn't fit into containing event entry's view.
Actually I see that the whole view, containing text, is shifted down and thus partially hidden...

So we need to redesign this view or maybe fix a way the Text scaling is done.
![Narrow-time-location](https://user-images.githubusercontent.com/207716/91937444-942a4a00-ecfa-11ea-8ede-2233fd27d7af.png)
The problem is evident when "Text size" is set to "Smallest" (see above). No problem, with default text size:
![Normal-height-normal-text-size](https://user-images.githubusercontent.com/207716/91937671-174ba000-ecfb-11ea-97d2-53382fe37074.png)

**Comment by volucris** [comment]
It's not just the details, it's the entire event. Events without time and place also get cropped. 
![Screenshot_20200902-090759__01](https://user-images.githubusercontent.com/12112767/91943018-2f6fef00-ecfc-11ea-9b22-c0534dfeedc7.jpg)

**Comment by yvolk** [comment]
Thank you all for reporting. I hope I fixed this layout in v.4.2.3, see #3 
?!
