### ISSUE TITLE
Very small text size results in clipped characters

### ISSUE THREAD

**Issue by siccovansas** [andstatus/todoagenda#46]
If I select 'Other settings > Text size > Very small', then some text of upcoming events will be clipped by the separator line between this and the next event, see the image below. This happens since version  4.2.2 and doesn't seem to happen with other text sizes (e.g., small).

![Screenshot_20200904-110354](https://user-images.githubusercontent.com/696839/92221894-73025e80-ee9e-11ea-8216-f6ec60ea3751.jpg)

**Comment by yvolk** [comment]
Hello @siccovansas , this is already fixed in v.4.2.3, see https://github.com/andstatus/todoagenda/issues/44

**Comment by siccovansas** [comment]
Aaah you are right! F-Droid just pushed 4.2.3 and it is fixed (and I didn't search the issues before posting mine 🙈). Thx!!
