### ISSUE TITLE
Show date for each entry (No dates without headings)

### ISSUE THREAD

**Issue by s-hamann** [andstatus/todoagenda#5]
When day headings are disabled, the dates of the entries are not shown anywhere.
I would prefer disabling the headings for a more concise overview, but the lack of date information makes this unable for me.

I think, when the headings are disabled, dates should be displayed with each entry.

**Comment by yvolk** [comment]
@s-hamann Actually, we do have an option to show a date of an entry in the Entry's line. It is called (in "Layout" section) "Show number of days to event" and it works, 
when "Event entry layout" is set to "All in one row". This is not an absolute date, but it takes much less space...
![Screenshot_1581137660](https://user-images.githubusercontent.com/207716/74079418-4d1bf500-4a48-11ea-8fc7-5bbaab921324.png)

**Comment by s-hamann** [comment]
@yvolk Yes, I tried that. I like the compact layout, but I need the absolute dates. The "countdown" simply does not comply with my way of thinking.

**Comment by yvolk** [comment]
I created separate ticket https://github.com/andstatus/todoagenda/issues/7 for a reusable Preference dialog that we could reuse for setting the Entry day format also (what is currently "Show number of days to event" checkbox.

**Comment by yvolk** [comment]
Beta version with Date formatting preference released. See https://github.com/andstatus/todoagenda/issues/7 and download from here: https://github.com/andstatus/todoagenda/issues/3

**Comment by yvolk** [comment]
Released in v.4.0.6
