### ISSUE TITLE
Todo Agenda widget not displaying birthdays anymore - Recently switched to Oneplus Nord

### ISSUE THREAD

**Issue by OneplusNord** [andstatus/todoagenda#52]
Hello, thanks for a great and useful product.

I have a question regarding the Todo Agenda widget, since I switched from a Oneplus 3T to a Oneplus Nord this week.
On the agenda widget I do not seem to see birthdays anymore, even with all calendars ticked on. Any idea how this can be resolved?

Thanks. Have a great day.

**Comment by yvolk** [comment]
Hello @OneplusNord , please look at this solution: https://github.com/andstatus/todoagenda/issues/37
