### ISSUE TITLE
Filters Issue

### ISSUE THREAD

**Issue by AndriiStepovyi** [andstatus/todoagenda#54]
Hey , Yuri!
Awesome app, using for years now.
Having an issue for awhile now- under EVENT FILTERS/SHOW PAST EVENTS to choose ENDED ONE WEEK AGO, and SHOW ALL PAST EVENTS HAVING THE DEFAULT COLOR - the first filter been ignored and widget shows ALL past events. Even if you will change it to YESTERDAY or any other. So past event of default color is not really about color-it does override the past even show settings in not the intended way, thus I understood.
![TodoAgenda_FilterON1](https://user-images.githubusercontent.com/11594037/95387780-38397f00-08bf-11eb-8c1f-ee521abb92a1.jpg)
![TodoAgenda_FilterOFF1](https://user-images.githubusercontent.com/11594037/95387788-3e2f6000-08bf-11eb-912a-109ea355da0b.jpg)
![ToDoAgenda_FilterON2](https://user-images.githubusercontent.com/11594037/95387804-42f41400-08bf-11eb-83e2-1e50285179ec.jpg)
![ToDoAgenda_filterOFF2](https://user-images.githubusercontent.com/11594037/95387813-46879b00-08bf-11eb-8c4f-0580aeaf0765.jpg)

{
  "deviceInfo": {
    "versionCode": 29,
    "versionRelease": "10",
    "versionCodename": "REL",
    "buildManufacturer": "samsung",
    "buildBrand": "samsung",
    "buildModel": "SM-G975F"
  },
  "applicationInfo": {
    "versionName": "4.3.1",
    "versionCode": 689
  },
  "settings": {
    "widgetId": 9,
    "widgetHeaderDateFormat": "defaultWeekday:",
    "widgetInstanceName": "Todo Agenda 9",
    "activeSources": [
      {
        "providerType": 1,
        "id": 5,
        "title": "Contacts",
        "summary": "andrey.stepovoy@gmail.com",
        "color": -7151168,
        "isAvailable": true
      },
      {
        "providerType": 1,
        "id": 7,
        "title": "Holidays in Ukraine",
        "summary": "andrey.stepovoy@gmail.com",
        "color": -15292571,
        "isAvailable": true
      },
      {
        "providerType": 1,
        "id": 8,
        "title": "Samsung Calendar",
        "summary": "andrey.stepovoy@gmail.com",
        "color": -16759123,
        "isAvailable": true
      },
      {
        "providerType": 3,
        "id": 1,
        "title": "Samsung Calendar",
        "summary": "Samsung Tasks",
        "color": -16738680,
        "isAvailable": true
      },
      {
        "providerType": 1,
        "id": 13,
        "title": "Contacts",
        "summary": "dr.stepovyi@gmail.com",
        "color": -7151168,
        "isAvailable": true
      },
      {
        "providerType": 1,
        "id": 5,
        "title": "Contacts",
        "summary": "andrey.stepovoy@gmail.com",
        "color": -7151168,
        "isAvailable": true
      },
      {
        "providerType": 1,
        "id": 15,
        "title": "dr.stepovyi@gmail.com",
        "summary": "dr.stepovyi@gmail.com",
        "color": -6299161,
        "isAvailable": true
      },
      {
        "providerType": 1,
        "id": 16,
        "title": "Contacts",
        "summary": "leoffice2007@gmail.com",
        "color": -7151168,
        "isAvailable": true
      },
      {
        "providerType": 1,
        "id": 18,
        "title": "leoffice2007@gmail.com",
        "summary": "leoffice2007@gmail.com",
        "color": -6644481,
        "isAvailable": true
      },
      {
        "providerType": 1,
        "id": 22,
        "title": "thestepovyis@gmail.com",
        "summary": "thestepovyis@gmail.com",
        "color": -339611,
        "isAvailable": true
      },
      {
        "providerType": 1,
        "id": 2,
        "title": "Mapk Степовой",
        "summary": "andrey.stepovoy@gmail.com",
        "color": -6644481,
        "isAvailable": true
      },
      {
        "providerType": 1,
        "id": 1,
        "title": "My calendar",
        "summary": "My calendar",
        "color": -11749922,
        "isAvailable": true
      },
      {
        "providerType": 1,
        "id": 3,
        "title": "Mr. & Mrs. Stepovyi",
        "summary": "andrey.stepovoy@gmail.com",
        "color": -3312410,
        "isAvailable": true
      },
      {
        "providerType": 1,
        "id": 23,
        "title": "Money In",
        "summary": "thestepovyis@gmail.com",
        "color": -370884,
        "isAvailable": true
      }
    ],
    "eventRange": 30,
    "eventsEnded": "ONE_WEEK",
    "fillAllDay": true,
    "hideBasedOnKeywords": "",
    "widgetHeaderBackgroundColor": 0,
    "pastEventsBackgroundColor": -1082623956,
    "todaysEventsBackgroundColor": -620756993,
    "backgroundColor": -2147483648,
    "headerTheme": "DARK",
    "dayHeaderThemePast": "DARK",
    "entryThemePast": "BLACK",
    "dayHeaderTheme": "LIGHT",
    "entryTheme": "WHITE",
    "dayHeaderThemeFuture": "DARK",
    "entryThemeFuture": "BLACK",
    "showDaysWithoutEvents": false,
    "showDayHeaders": true,
    "dayHeaderDateFormat": "defaultWeekday:",
    "horizontalLineBelowDayHeader": false,
    "showPastEventsUnderOneHeader": false,
    "showPastEventsWithDefaultColor": false,
    "showEventIcon": true,
    "entryDateFormat": "days:bbbb",
    "showEndTime": true,
    "showLocation": true,
    "dateFormat": "24",
    "lockedTimeZoneId": "America\/New_York",
    "snapshotMode": "live_data",
    "refreshPeriodMinutes": 10,
    "eventEntryLayout": "DEFAULT",
    "multiline_title": false,
    "multiline_details": false,
    "showOnlyClosestInstanceOfRecurringEvent": false,
    "hideDuplicates": false,
    "allDayEventsPlacement": "top_day",
    "taskScheduling": "date_due",
    "taskWithoutDates": "end_of_list",
    "filterMode": "normal",
    "indicateAlerts": true,
    "indicateRecurring": false,
    "compactLayout": false,
    "widgetHeaderLayout": "ONE_ROW",
    "textSizeScale": "1.0",
    "dayHeaderAlignment": "RIGHT"
  },
  "resultsVersion": 3,
  "results": [
    {
      "providerType": 1,
      "executedAt": 1602104740417,
      "timeZoneId": "America\/New_York",
      "millisOffsetUtcToLocal": -14400000,
      "standardMillisOffsetUtcToLocal": -18000000,
      "uri": "content:\/\/com.android.calendar\/instances\/when\/1601438400000\/1604700340417",
      "projection": [
        "calendar_id",
        "event_id",
        "title",
        "begin",
        "end",
        "allDay",
        "eventLocation",
        "hasAlarm",
        "rrule",
        "displayColor",
        "calendar_color"
      ],
      "selection": "selfAttendeeStatus!=2 AND (calendar_id = 5 OR calendar_id = 7 OR calendar_id = 8 OR calendar_id = 13 OR calendar_id = 5 OR calendar_id = 15 OR calendar_id = 16 OR calendar_id = 18 OR calendar_id = 22 OR calendar_id = 2 OR calendar_id = 1 OR calendar_id = 3 OR calendar_id = 23 )",
      "selectionArgs": [],
      "sortOrder": "startDay ASC, allDay DESC, begin ASC ",
      "rows": [
        {
          "allDay": {
            "type": 1,
            "value": 1
          },
          "rrule": {
            "type": 3,
            "value": "FREQ=MONTHLY;WKST=MO"
          },
          "event_id": {
            "type": 1,
            "value": 461
          },
          "calendar_id": {
            "type": 1,
            "value": 22
          },
          "eventLocation": {
            "type": 3,
            "value": ""
          },
          "end": {
            "type": 1,
            "value": 1601596800000
          },
          "displayColor": {
            "type": 1,
            "value": -339611
          },
          "title": {
            "type": 3,
            "value": "PAY OMF: $220"
          },
          "begin": {
            "type": 1,
            "value": 1601510400000
          },
          "hasAlarm": {
            "type": 1,
            "value": 0
          },
          "calendar_color": {
            "type": 1,
            "value": -339611
          }
        },
        {
          "allDay": {
            "type": 1,
            "value": 1
          },
          "rrule": {
            "type": 3,
            "value": "FREQ=MONTHLY;WKST=MO"
          },
          "event_id": {
            "type": 1,
            "value": 705
          },
          "calendar_id": {
            "type": 1,
            "value": 22
          },
          "eventLocation": {
            "type": 3,
            "value": ""
          },
          "end": {
            "type": 1,
            "value": 1601596800000
          },
          "displayColor": {
            "type": 1,
            "value": -339611
          },
          "title": {
            "type": 3,
            "value": "PAY STUDIO: $134"
          },
          "begin": {
            "type": 1,
            "value": 1601510400000
          },
          "hasAlarm": {
            "type": 1,
            "value": 0
          },
          "calendar_color": {
            "type": 1,
            "value": -339611
          }
        },
        {
          "allDay": {
            "type": 1,
            "value": 1
          },
          "rrule": {
            "type": 3,
            "value": "FREQ=WEEKLY;INTERVAL=2;WKST=SU;BYDAY=FR"
          },
          "event_id": {
            "type": 1,
            "value": 786
          },
          "calendar_id": {
            "type": 1,
            "value": 23
          },
          "eventLocation": {
            "type": 3,
            "value": ""
          },
          "end": {
            "type": 1,
            "value": 1601683200000
          },
          "displayColor": {
            "type": 1,
            "value": -370884
          },
          "title": {
            "type": 3,
            "value": "$671"
          },
          "begin": {
            "type": 1,
            "value": 1601596800000
          },
          "hasAlarm": {
            "type": 1,
            "value": 0
          },
          "calendar_color": {
            "type": 1,
            "value": -370884
          }
        },
        {
          "allDay": {
            "type": 1,
            "value": 1
          },
          "event_id": {
            "type": 1,
            "value": 360
          },
          "calendar_id": {
            "type": 1,
            "value": 7
          },
          "eventLocation": {
            "type": 3,
            "value": ""
          },
          "end": {
            "type": 1,
            "value": 1601856000000
          },
          "displayColor": {
            "type": 1,
            "value": -15292571
          },
          "title": {
            "type": 3,
            "value": "Teacher's Day"
          },
          "begin": {
            "type": 1,
            "value": 1601769600000
          },
          "hasAlarm": {
            "type": 1,
            "value": 0
          },
          "calendar_color": {
            "type": 1,
            "value": -15292571
          }
        },
        {
          "allDay": {
            "type": 1,
            "value": 1
          },
          "rrule": {
            "type": 3,
            "value": "FREQ=MONTHLY;WKST=MO"
          },
          "event_id": {
            "type": 1,
            "value": 700
          },
          "calendar_id": {
            "type": 1,
            "value": 22
          },
          "eventLocation": {
            "type": 3,
            "value": ""
          },
          "end": {
            "type": 1,
            "value": 1601856000000
          },
          "displayColor": {
            "type": 1,
            "value": -339611
          },
          "title": {
            "type": 3,
            "value": " PAY NETFLIX: $14.22"
          },
          "begin": {
            "type": 1,
            "value": 1601769600000
          },
          "hasAlarm": {
            "type": 1,
            "value": 0
          },
          "calendar_color": {
            "type": 1,
            "value": -339611
          }
        },
        {
          "allDay": {
            "type": 1,
            "value": 1
          },
          "rrule": {
            "type": 3,
            "value": "FREQ=DAILY;INTERVAL=13;WKST=MO"
          },
          "event_id": {
            "type": 1,
            "value": 720
          },
          "calendar_id": {
            "type": 1,
            "value": 22
          },
          "eventLocation": {
            "type": 3,
            "value": ""
          },
          "end": {
            "type": 1,
            "value": 1601856000000
          },
          "displayColor": {
            "type": 1,
            "value": -339611
          },
          "title": {
            "type": 3,
            "value": "PAY CAR: $208"
          },
          "begin": {
            "type": 1,
            "value": 1601769600000
          },
          "hasAlarm": {
            "type": 1,
            "value": 0
          },
          "calendar_color": {
            "type": 1,
            "value": -339611
          }
        },
        {
          "allDay": {
            "type": 1,
            "value": 1
          },
          "rrule": {
            "type": 3,
            "value": "FREQ=MONTHLY;WKST=MO"
          },
          "event_id": {
            "type": 1,
            "value": 704
          },
          "calendar_id": {
            "type": 1,
            "value": 22
          },
          "eventLocation": {
            "type": 3,
            "value": ""
          },
          "end": {
            "type": 1,
            "value": 1602028800000
          },
          "displayColor": {
            "type": 1,
            "value": -339611
          },
          "title": {
            "type": 3,
            "value": " PAY GODADDY: $10"
          },
          "begin": {
            "type": 1,
            "value": 1601942400000
          },
          "hasAlarm": {
            "type": 1,
            "value": 0
          },
          "calendar_color": {
            "type": 1,
            "value": -339611
          }
        },
        {
          "allDay": {
            "type": 1,
            "value": 0
          },
          "rrule": {
            "type": 3,
            "value": "FREQ=WEEKLY;INTERVAL=2;WKST=SU;BYDAY=TU"
          },
          "event_id": {
            "type": 1,
            "value": 816
          },
          "calendar_id": {
            "type": 1,
            "value": 3
          },
          "eventLocation": {
            "type": 3,
            "value": ""
          },
          "end": {
            "type": 1,
            "value": 1601996400000
          },
          "displayColor": {
            "type": 1,
            "value": -3312410
          },
          "title": {
            "type": 3,
            "value": "Garbage Out+ Recyclables"
          },
          "begin": {
            "type": 1,
            "value": 1601992800000
          },
          "hasAlarm": {
            "type": 1,
            "value": 1
          },
          "calendar_color": {
            "type": 1,
            "value": -3312410
          }
        },
        {
          "allDay": {
            "type": 1,
            "value": 0
          },
          "event_id": {
            "type": 1,
            "value": 874
          },
          "calendar_id": {
            "type": 1,
            "value": 22
          },
          "eventLocation": {
            "type": 3,
            "value": ""
          },
          "end": {
            "type": 1,
            "value": 1602165600000
          },
          "displayColor": {
            "type": 1,
            "value": -339611
          },
          "title": {
            "type": 3,
            "value": "Tommy Printing"
          },
          "begin": {
            "type": 1,
            "value": 1602162000000
          },
          "hasAlarm": {
            "type": 1,
            "value": 1
          },
          "calendar_color": {
            "type": 1,
            "value": -339611
          }
        },
        {
          "allDay": {
            "type": 1,
            "value": 0
          },
          "event_id": {
            "type": 1,
            "value": 832
          },
          "calendar_id": {
            "type": 1,
            "value": 2
          },
          "eventLocation": {
            "type": 3,
            "value": ""
          },
          "end": {
            "type": 1,
            "value": 1602183600000
          },
          "displayColor": {
            "type": 1,
            "value": -6644481
          },
          "title": {
            "type": 3,
            "value": "ITProTV: haching IP camera webinar"
          },
          "begin": {
            "type": 1,
            "value": 1602180000000
          },
          "hasAlarm": {
            "type": 1,
            "value": 1
          },
          "calendar_color": {
            "type": 1,
            "value": -6644481
          }
        },
        {
          "allDay": {
            "type": 1,
            "value": 0
          },
          "rrule": {
            "type": 3,
            "value": "FREQ=WEEKLY;INTERVAL=2;WKST=SU;BYDAY=TU"
          },
          "event_id": {
            "type": 1,
            "value": 815
          },
          "calendar_id": {
            "type": 1,
            "value": 3
          },
          "eventLocation": {
            "type": 3,
            "value": ""
          },
          "end": {
            "type": 1,
            "value": 1602601200000
          },
          "displayColor": {
            "type": 1,
            "value": -3312410
          },
          "title": {
            "type": 3,
            "value": "Garbage out: Waste"
          },
          "begin": {
            "type": 1,
            "value": 1602597600000
          },
          "hasAlarm": {
            "type": 1,
            "value": 1
          },
          "calendar_color": {
            "type": 1,
            "value": -3312410
          }
        },
        {
          "allDay": {
            "type": 1,
            "value": 1
          },
          "event_id": {
            "type": 1,
            "value": 361
          },
          "calendar_id": {
            "type": 1,
            "value": 7
          },
          "eventLocation": {
            "type": 3,
            "value": ""
          },
          "end": {
            "type": 1,
            "value": 1602720000000
          },
          "displayColor": {
            "type": 1,
            "value": -15292571
          },
          "title": {
            "type": 3,
            "value": "Defenders' Day"
          },
          "begin": {
            "type": 1,
            "value": 1602633600000
          },
          "hasAlarm": {
            "type": 1,
            "value": 0
          },
          "calendar_color": {
            "type": 1,
            "value": -15292571
          }
        },
        {
          "allDay": {
            "type": 1,
            "value": 1
          },
          "rrule": {
            "type": 3,
            "value": "FREQ=WEEKLY;INTERVAL=2;WKST=SU;BYDAY=FR"
          },
          "event_id": {
            "type": 1,
            "value": 786
          },
          "calendar_id": {
            "type": 1,
            "value": 23
          },
          "eventLocation": {
            "type": 3,
            "value": ""
          },
          "end": {
            "type": 1,
            "value": 1602892800000
          },
          "displayColor": {
            "type": 1,
            "value": -370884
          },
          "title": {
            "type": 3,
            "value": "$671"
          },
          "begin": {
            "type": 1,
            "value": 1602806400000
          },
          "hasAlarm": {
            "type": 1,
            "value": 0
          },
          "calendar_color": {
            "type": 1,
            "value": -370884
          }
        },
        {
          "allDay": {
            "type": 1,
            "value": 1
          },
          "rrule": {
            "type": 3,
            "value": "FREQ=DAILY;INTERVAL=13;WKST=MO"
          },
          "event_id": {
            "type": 1,
            "value": 720
          },
          "calendar_id": {
            "type": 1,
            "value": 22
          },
          "eventLocation": {
            "type": 3,
            "value": ""
          },
          "end": {
            "type": 1,
            "value": 1602979200000
          },
          "displayColor": {
            "type": 1,
            "value": -339611
          },
          "title": {
            "type": 3,
            "value": "PAY CAR: $208"
          },
          "begin": {
            "type": 1,
            "value": 1602892800000
          },
          "hasAlarm": {
            "type": 1,
            "value": 0
          },
          "calendar_color": {
            "type": 1,
            "value": -339611
          }
        },
        {
          "allDay": {
            "type": 1,
            "value": 1
          },
          "rrule": {
            "type": 3,
            "value": "FREQ=MONTHLY;WKST=MO"
          },
          "event_id": {
            "type": 1,
            "value": 706
          },
          "calendar_id": {
            "type": 1,
            "value": 22
          },
          "eventLocation": {
            "type": 3,
            "value": ""
          },
          "end": {
            "type": 1,
            "value": 1603238400000
          },
          "displayColor": {
            "type": 1,
            "value": -339611
          },
          "title": {
            "type": 3,
            "value": "PAY PRIME: $14"
          },
          "begin": {
            "type": 1,
            "value": 1603152000000
          },
          "hasAlarm": {
            "type": 1,
            "value": 0
          },
          "calendar_color": {
            "type": 1,
            "value": -339611
          }
        },
        {
          "allDay": {
            "type": 1,
            "value": 0
          },
          "rrule": {
            "type": 3,
            "value": "FREQ=WEEKLY;INTERVAL=2;WKST=SU;BYDAY=TU"
          },
          "event_id": {
            "type": 1,
            "value": 816
          },
          "calendar_id": {
            "type": 1,
            "value": 3
          },
          "eventLocation": {
            "type": 3,
            "value": ""
          },
          "end": {
            "type": 1,
            "value": 1603206000000
          },
          "displayColor": {
            "type": 1,
            "value": -3312410
          },
          "title": {
            "type": 3,
            "value": "Garbage Out+ Recyclables"
          },
          "begin": {
            "type": 1,
            "value": 1603202400000
          },
          "hasAlarm": {
            "type": 1,
            "value": 1
          },
          "calendar_color": {
            "type": 1,
            "value": -3312410
          }
        },
        {
          "allDay": {
            "type": 1,
            "value": 1
          },
          "event_id": {
            "type": 1,
            "value": 362
          },
          "calendar_id": {
            "type": 1,
            "value": 7
          },
          "eventLocation": {
            "type": 3,
            "value": ""
          },
          "end": {
            "type": 1,
            "value": 1603670400000
          },
          "displayColor": {
            "type": 1,
            "value": -15292571
          },
          "title": {
            "type": 3,
            "value": "Daylight Saving Time ends"
          },
          "begin": {
            "type": 1,
            "value": 1603584000000
          },
          "hasAlarm": {
            "type": 1,
            "value": 0
          },
          "calendar_color": {
            "type": 1,
            "value": -15292571
          }
        },
        {
          "allDay": {
            "type": 1,
            "value": 0
          },
          "rrule": {
            "type": 3,
            "value": "FREQ=WEEKLY;INTERVAL=2;WKST=SU;BYDAY=TU"
          },
          "event_id": {
            "type": 1,
            "value": 815
          },
          "calendar_id": {
            "type": 1,
            "value": 3
          },
          "eventLocation": {
            "type": 3,
            "value": ""
          },
          "end": {
            "type": 1,
            "value": 1603810800000
          },
          "displayColor": {
            "type": 1,
            "value": -3312410
          },
          "title": {
            "type": 3,
            "value": "Garbage out: Waste"
          },
          "begin": {
            "type": 1,
            "value": 1603807200000
          },
          "hasAlarm": {
            "type": 1,
            "value": 1
          },
          "calendar_color": {
            "type": 1,
            "value": -3312410
          }
        },
        {
          "allDay": {
            "type": 1,
            "value": 1
          },
          "rrule": {
            "type": 3,
            "value": "FREQ=MONTHLY;WKST=MO"
          },
          "event_id": {
            "type": 1,
            "value": 703
          },
          "calendar_id": {
            "type": 1,
            "value": 22
          },
          "eventLocation": {
            "type": 3,
            "value": ""
          },
          "end": {
            "type": 1,
            "value": 1604016000000
          },
          "displayColor": {
            "type": 1,
            "value": -339611
          },
          "title": {
            "type": 3,
            "value": "PAY CAR INSURANCE: $93"
          },
          "begin": {
            "type": 1,
            "value": 1603929600000
          },
          "hasAlarm": {
            "type": 1,
            "value": 0
          },
          "calendar_color": {
            "type": 1,
            "value": -339611
          }
        },
        {
          "allDay": {
            "type": 1,
            "value": 1
          },
          "rrule": {
            "type": 3,
            "value": "FREQ=DAILY;INTERVAL=13;WKST=MO"
          },
          "event_id": {
            "type": 1,
            "value": 720
          },
          "calendar_id": {
            "type": 1,
            "value": 22
          },
          "eventLocation": {
            "type": 3,
            "value": ""
          },
          "end": {
            "type": 1,
            "value": 1604102400000
          },
          "displayColor": {
            "type": 1,
            "value": -339611
          },
          "title": {
            "type": 3,
            "value": "PAY CAR: $208"
          },
          "begin": {
            "type": 1,
            "value": 1604016000000
          },
          "hasAlarm": {
            "type": 1,
            "value": 0
          },
          "calendar_color": {
            "type": 1,
            "value": -339611
          }
        },
        {
          "allDay": {
            "type": 1,
            "value": 1
          },
          "rrule": {
            "type": 3,
            "value": "FREQ=WEEKLY;INTERVAL=2;WKST=SU;BYDAY=FR"
          },
          "event_id": {
            "type": 1,
            "value": 786
          },
          "calendar_id": {
            "type": 1,
            "value": 23
          },
          "eventLocation": {
            "type": 3,
            "value": ""
          },
          "end": {
            "type": 1,
            "value": 1604102400000
          },
          "displayColor": {
            "type": 1,
            "value": -370884
          },
          "title": {
            "type": 3,
            "value": "$671"
          },
          "begin": {
            "type": 1,
            "value": 1604016000000
          },
          "hasAlarm": {
            "type": 1,
            "value": 0
          },
          "calendar_color": {
            "type": 1,
            "value": -370884
          }
        },
        {
          "allDay": {
            "type": 1,
            "value": 1
          },
          "rrule": {
            "type": 3,
            "value": "FREQ=MONTHLY;WKST=MO"
          },
          "event_id": {
            "type": 1,
            "value": 461
          },
          "calendar_id": {
            "type": 1,
            "value": 22
          },
          "eventLocation": {
            "type": 3,
            "value": ""
          },
          "end": {
            "type": 1,
            "value": 1604275200000
          },
          "displayColor": {
            "type": 1,
            "value": -339611
          },
          "title": {
            "type": 3,
            "value": "PAY OMF: $220"
          },
          "begin": {
            "type": 1,
            "value": 1604188800000
          },
          "hasAlarm": {
            "type": 1,
            "value": 0
          },
          "calendar_color": {
            "type": 1,
            "value": -339611
          }
        },
        {
          "allDay": {
            "type": 1,
            "value": 1
          },
          "rrule": {
            "type": 3,
            "value": "FREQ=MONTHLY;WKST=MO"
          },
          "event_id": {
            "type": 1,
            "value": 705
          },
          "calendar_id": {
            "type": 1,
            "value": 22
          },
          "eventLocation": {
            "type": 3,
            "value": ""
          },
          "end": {
            "type": 1,
            "value": 1604275200000
          },
          "displayColor": {
            "type": 1,
            "value": -339611
          },
          "title": {
            "type": 3,
            "value": "PAY STUDIO: $134"
          },
          "begin": {
            "type": 1,
            "value": 1604188800000
          },
          "hasAlarm": {
            "type": 1,
            "value": 0
          },
          "calendar_color": {
            "type": 1,
            "value": -339611
          }
        },
        {
          "allDay": {
            "type": 1,
            "value": 0
          },
          "rrule": {
            "type": 3,
            "value": "FREQ=WEEKLY;INTERVAL=2;WKST=SU;BYDAY=TU"
          },
          "event_id": {
            "type": 1,
            "value": 816
          },
          "calendar_id": {
            "type": 1,
            "value": 3
          },
          "eventLocation": {
            "type": 3,
            "value": ""
          },
          "end": {
            "type": 1,
            "value": 1604419200000
          },
          "displayColor": {
            "type": 1,
            "value": -3312410
          },
          "title": {
            "type": 3,
            "value": "Garbage Out+ Recyclables"
          },
          "begin": {
            "type": 1,
            "value": 1604415600000
          },
          "hasAlarm": {
            "type": 1,
            "value": 1
          },
          "calendar_color": {
            "type": 1,
            "value": -3312410
          }
        },
        {
          "allDay": {
            "type": 1,
            "value": 1
          },
          "rrule": {
            "type": 3,
            "value": "FREQ=MONTHLY;WKST=MO"
          },
          "event_id": {
            "type": 1,
            "value": 700
          },
          "calendar_id": {
            "type": 1,
            "value": 22
          },
          "eventLocation": {
            "type": 3,
            "value": ""
          },
          "end": {
            "type": 1,
            "value": 1604534400000
          },
          "displayColor": {
            "type": 1,
            "value": -339611
          },
          "title": {
            "type": 3,
            "value": " PAY NETFLIX: $14.22"
          },
          "begin": {
            "type": 1,
            "value": 1604448000000
          },
          "hasAlarm": {
            "type": 1,
            "value": 0
          },
          "calendar_color": {
            "type": 1,
            "value": -339611
          }
        },
        {
          "allDay": {
            "type": 1,
            "value": 1
          },
          "rrule": {
            "type": 3,
            "value": "FREQ=MONTHLY;WKST=MO"
          },
          "event_id": {
            "type": 1,
            "value": 704
          },
          "calendar_id": {
            "type": 1,
            "value": 22
          },
          "eventLocation": {
            "type": 3,
            "value": ""
          },
          "end": {
            "type": 1,
            "value": 1604707200000
          },
          "displayColor": {
            "type": 1,
            "value": -339611
          },
          "title": {
            "type": 3,
            "value": " PAY GODADDY: $10"
          },
          "begin": {
            "type": 1,
            "value": 1604620800000
          },
          "hasAlarm": {
            "type": 1,
            "value": 0
          },
          "calendar_color": {
            "type": 1,
            "value": -339611
          }
        }
      ]
    },
    {
      "providerType": 3,
      "executedAt": 1602104740432,
      "timeZoneId": "America\/New_York",
      "millisOffsetUtcToLocal": -14400000,
      "standardMillisOffsetUtcToLocal": -18000000,
      "uri": "content:\/\/com.android.calendar\/syncTasks",
      "projection": [
        "_id",
        "subject",
        "utc_due_date",
        "secAccountColor",
        "accountKey"
      ],
      "selection": "deleted = 0 AND complete = 0 AND accountKey IN ( 1 )",
      "selectionArgs": [],
      "sortOrder": "",
      "rows": []
    }
  ]
}

**Comment by yvolk** [comment]
Hello @AndriiStepovyi,

The first filter is ignored ONLY for past events, having default color.
This means that:

If you set:
1. "Show past events" to "Ended yesterday" 
and
2. "Show all past events having default color" is on

Then All past events that are older than yesterday have default color.

I just checked this: I edited some older event: changed its color from Default to Grey - and refreshed the widget: the event disappeared.

**Comment by AndriiStepovyi** [comment]
Sorry, I responded in another mail but just now I got what you was saying. So First filter is basically allows to show all events prior to the filter YESTERDAY, ONE WEEK AGO and so on in different the default color, but not filtering the display of events as such- to show/not to show like at all! I see now! Thanks.
--
Best Regards

Andrii Stepovyi
