### ISSUE TITLE
Refining alignment.

### ISSUE THREAD

**Issue by Kolorado67** [andstatus/todoagenda#58]
Would it be possible to have the widget's overall vertical size adjust automatically to the events displayed. I find myself adjusting the text size and the information displayed so it best fits the frame.
The preset sizes don't seem to consider the data being displayed. I am probably being very picky about this, but I think it's worth asking. 
Thanks.
![Screenshot_20201122-134856~2](https://user-images.githubusercontent.com/74865011/99906062-b9f93680-2ccc-11eb-9b1b-c22f28071c80.jpg)
![Screenshot_20201122-134908~2](https://user-images.githubusercontent.com/74865011/99906066-c087ae00-2ccc-11eb-8a24-3371b63b8425.jpg)

**Comment by yvolk** [comment]
Hi @Kolorado67, in your example it's simply slightly not enough space for the widget to show two events completely.
No, Android doesn't allow to increase widget's size automatically: you need to make a widget taller by one predefined "position" to reserve extra vertical space.

Or you can decrease size of the widget's content. We have several means for this, including
Other settings -> Text size
Layout -> Compact layout

**Comment by Kolorado67** [comment]
Thanks for the feedback. I think by tweaking the available options I have got it to a point that works. 👍
