### ISSUE TITLE
[feature request]: option for adding new Tasks' local lists automatically

### ISSUE THREAD

**Issue by just-Nob** [andstatus/todoagenda#64]
I like to have a separate todo widget with all that tasks displayed which I'm managing in _Tasks_ (tasks.org).

To implement this, all of _Tasks'_ local lists must be activated in _Todo Agenda_. As soon as I create a new list in _Tasks_, I have to add it to the widget. I add new lists relatively often, because I typically create a new list for each new project.
If I forget to do this, the entries of the new list do not show up in the widget.

Therefore, I would like to have an option that always automatically activates all (newly) defined local lists in the widget.

**Comment by yvolk** [comment]
I would suggest to create some combined list "Tasks from all my local lists" at the Tasks app side. This would be controllable, easy to understand. It the Tasks app doesn't allow to have such a feature, it need to be implemented...
