### ISSUE TITLE
Tasks not shown when Tasks app closed

### ISSUE THREAD

**Issue by Fessus** [andstatus/todoagenda#66]
I'm experiencing the issue, that as long as the [Tasks app](https://github.com/tasks/tasks#readme) is closed, no tasks are shown in the widget.
When its open in the background, after hitting the refresh button on the widget, all tasks appear again as they should.

The calendar events are shown regardless if the calendar app itself is opened or not.

~Edit: Actually, I have to correct my statement. The described behavior only happens, when the local lists in the [Tasks app](https://github.com/tasks/tasks#readme) are deactivated. As soon as it is reactivated, the widget behaves normal again.~
_Edit: When the task app is closed, it says "Not found" in front of the lists name (in the settings when choosing which calendars/task lists shall be shown in the widget)._

**Comment by abaker** [comment]
If Tasks is being killed in the background that would probably prevent ToDo Agenda from fetching tasks. If you think that might be the case check out dontkillmyapp.com
