### ISSUE TITLE
OpenTask crashs when opened through Todo Agenda Widget 

### ISSUE THREAD

**Issue by uSyzex** [andstatus/todoagenda#69]
Info:
Android 9.0 
OpenTasks 1.4.2 (last update available)
Todo Agenda 4.4.0 (last update available)
Both apps have been downloaded from Fdroid.

Description of the problem:
I can access Events from Etar through the widget.
But when I click on a Task from OpenTasks through the widget, nothing happens and I receive the message "OpenTasks keeps stopping" offering me two options: "App info" and "Close app". Otherwise, OpenTasks works well alone.

I already tried:
- Reinstalling both apps
- Change versions of Todo Agenda ( i use to be on the version of old android vers)

If I can provide any additional information, ask me and I will.

Regards

**Comment by yvolk** [comment]
Hi @uSyzex 
Looks like this issue should be put into OpenTasks app issue list.

**Comment by uSyzex** [comment]
> 
> 
> Hi @uSyzex
> Looks like this issue should be put into OpenTasks app issue list.

AS OpenTask worked fine alone, I tought It was a good idea to post it here first. 
I'm going to post it to OpenTasks issue list, thank you.

**Comment by yvolk** [comment]
@uSyzex I think that OpenTasks app should not crash, even if our widget makes somewhat invalid call. It should allow to diagnose a problem somehow, e.g. write an error description into a log.
So we could figure out, what's wrong.

**Comment by glemco** [comment]
The dev of OpenTask also pointed out a problem in TodoAgenda related with this. If you didn't see this yet, it may be helpful (https://github.com/dmfs/opentasks/issues/1015).

**Comment by uSyzex** [comment]
> 
> 
> The dev of OpenTask also pointed out a problem in TodoAgenda related with this. If you didn't see this yet, it may be helpful ([dmfs/opentasks#1015](https://github.com/dmfs/opentasks/issues/1015)).

You're right, thank you very much. As the developper akwnoledged it, I will close this issue and let the other one open for visibility.  Thanks again, have a great day ! 

@yvolk I don't have the knowledge to guide you but @dmfs suggests this: 
https://github.com/dmfs/opentasks/issues/1015#issuecomment-803101994

I hope it can help you imrove the app, which is already wonderful. Thank you very much for you work

**Comment by yvolk** [comment]
@glemco @uSyzex Ok, so we see that a change in the OpenTasks app broke interface (contract) with widgets and as a result we have OpenTasks' crash and no data from it in ToDo Agenda widget.

Normal solution of this problem should be allowing OpenTasks to process "the old way" requests correctly to preserve compatibility: users not always want to update both apps simultaneously, so this fix will allow to update OpenTasks app without updating the widget.
At least OpenTasks should not crash, but instead should tell a User that it's not compatible with a widget anymore... to avoid users' confusion and disappointment.

I wrote the same in the OpenTasks' issue https://github.com/dmfs/opentasks/issues/1015 hoping that its developer will fix the compatibility problem with current version of our widget.

Implementing newer OpenTasks' interface in the ToDo Agenda widget is a separate work...
