### ISSUE TITLE
[feature request] Filter specific calendar entries

### ISSUE THREAD

**Issue by kingmustard** [andstatus/todoagenda#70]
Is it possible to filter specific calendar entries from appearing in the widget?

**Comment by yvolk** [comment]
I assume that you saw all existing filtering options, including "Hide based on keywords in a title".
You can choose your own keyword to use in a title of a calendar event to be hidden in the widget. Adding that keyword to a title will hide the calendar entry in the selected widget.

**Comment by kingmustard** [comment]
> I assume that you saw all existing filtering options, including "Hide based on keywords in a title".
> You can choose your own keyword to use in a title of a calendar event to be hidden in the widget. Adding that keyword to a title will hide the calendar entry in the selected widget.

Somehow, I completely missed that!

I have added 'Catchup' to 'Hide based on keywords in a title' and waited 30 minutes but they're all still appearing in the widget. Any ideas?

**Comment by yvolk** [comment]
1. Please try to refresh the widget clicking on "refresh" button on the widget's header.
2. Re-enter the widget settings and check the keyword in a filer.

I just did this and it worked for me.

**Comment by kingmustard** [comment]
> 1. Please try to refresh the widget clicking on "refresh" button on the widget's header.
> 2. Re-enter the widget settings and check the keyword in a filer.
> 
> I just did this and it worked for me.

Ah, just found out it's case sensitive 😊

All sorted. Excellent piece of software!
