### ISSUE TITLE
failing to open OpenTasks

### ISSUE THREAD

**Issue by ilippert** [andstatus/todoagenda#73]
I run todoagenda 4.4.0 and OpenTasks 1.4.2.

When tapping onto a task in the agenda widget, OpenTasks is not called correctly. Though manually calling OpenTasks works.

This is the first time I report something here, please let me know if you like more information. Thanks!

**Comment by yvolk** [comment]
Hello @ilippert 
Thanks for posting! Please look at this issue: it is exactly about compatibility problem caused by recent braking changes in OpenTasks: https://github.com/andstatus/todoagenda/issues/69

**Comment by ilippert** [comment]
thanks a lot!
