### ISSUE TITLE
[feature request] option to put the date in a column next to the task (left/right?) as well as above task

### ISSUE THREAD

**Issue by Blubbey** [andstatus/todoagenda#74]
Layout could be something like:

19 Jul | Task name
Wed    | Task time

With the date/day having the same font size and colour of the task name/time respectively, or their own own variable(s) whichever is easier

**Comment by yvolk** [comment]
@Blubbey You can achieve this with this:

Layout:
- Turn off Day header
- Event entry layout: "All in one row"
- Entry date format: Custom pattern: dd MMM

Event details:
- Turn off "End time"

Start time (if set) is still visible though...
![Screenshot_20210801-093612](https://user-images.githubusercontent.com/207716/127761889-c7771719-e11e-45d3-a4b7-5cd49768b71a.png)
