### ISSUE TITLE
Weeknumber is 1 to high

### ISSUE THREAD

**Issue by DUbb73** [andstatus/todoagenda#77]
Is it possible to choose between normal weeknum and iso weeknum? They have a difference of 1.

**Comment by yvolk** [comment]
@DUbb73 I guess that you mean date formatting described here: https://github.com/andstatus/todoagenda/issues/7
Week numbers are produced by Android system's "Simple date format" feature that doesn't have such an option listed (yet...)

**Comment by DUbb73** [comment]
Thanks for your reply @yvolk, it pointed me in the right direcion.
I've changed the system language of my android phone from "Englisch (United states)" to "Englisch (Netherlands)",
Now the weeknumber is correct (also the week starts on Monday not on Sunday).

**Comment by yvolk** [comment]
@DUbb73 Thank you for the feedback. Interesting observation.
