### ISSUE TITLE
Do not make all permissions mandatory

### ISSUE THREAD

**Issue by Glitchy-Tozier** [andstatus/todoagenda#80]
This screen pops up when i click in the app-icon. This is a good thing, but it shouldn't be mandatory, imo. Some people just don't use tasks, thus making forcing this permission into the user overkill.

![Screenshot_20210930-074022_Todo Agenda.jpg](https://user-images.githubusercontent.com/59611881/135394373-5474d5e3-93f0-4a81-9932-8303708f187e.jpg)

Those two are the problematic permissions:
![Screenshot_20210930-074628_Google Play Store.jpg](https://user-images.githubusercontent.com/59611881/135394548-84b85b05-cec7-437d-b8a1-eeb141e63a98.jpg)

**Comment by yvolk** [comment]
@Glitchy-Tozier There is no point in the widget if it is not permitted to show anything. As I remember, it's mandatory for our Widget to have permissions for Calendar events OR for Tasks. I.e. at least for something that it could show.
Please check!

And please, switch to English interface and post screenshots in English. Otherwise I'm afraid we will misunderstand each other.

**Comment by Glitchy-Tozier** [comment]
The widget already has calendar-permission, and it *does* show events.
Here's a few screenshots:

![20211001_080819.jpg](https://user-images.githubusercontent.com/59611881/135573666-68b457ba-f5b0-4d37-b2d0-aa41075afd32.jpg)

![Screenshot_20211001-080616_Todo Agenda.jpg](https://user-images.githubusercontent.com/59611881/135573680-648a519d-be99-4d73-a196-ef08e448d92c.jpg)

![Screenshot_20211001-080714_Permission controller.jpg](https://user-images.githubusercontent.com/59611881/135573692-0a33b5b5-ccdb-4496-8e3a-cf72c69fbf52.jpg)

**Comment by yvolk** [comment]
Please try to explicitly deny permissions for tasks (something like "deny and don't remind me anymore...").
This should work.
?!

**Comment by Glitchy-Tozier** [comment]
It didn't. The screen still shows up. (only the popup doesn't show up anymore)

**Comment by Glitchy-Tozier** [comment]
I think it'll just be something that is wrong with the code. The page probably always shows up, unless ALL permissions were given. This should be fixed.

**Comment by yvolk** [comment]
Hello @Glitchy-Tozier!
Thank you again for your report, at last I fixed this problem (I hope) by mostly rewriting what the app does to check, to present and to fix permission problems.

When no permissions allowed:
![grant-permissions-4-8](https://github.com/andstatus/todoagenda/assets/207716/b2362a56-c3bc-409c-b9ee-e2158bc604f3)

When at least one permission is allowed:
![grant-permissions-tasks-only-4-8](https://github.com/andstatus/todoagenda/assets/207716/752e9791-86a1-4366-a4c4-646e5a63313a)


I posted v.4.8.0 to https://github.com/andstatus/todoagenda/releases/tag/4.8.0-release

**Comment by Glitchy-Tozier** [comment]
Sounds great, I'll test it when it arrives in the store 👍🏻

**Comment by Glitchy-Tozier** [comment]
Just got the update, it works great! Thank you! :)
