### ISSUE TITLE
When clicking the widget header, making the widget open the "Etar Agenda" calendar app in a preferred view than daily

### ISSUE THREAD

**Issue by Kalytis** [andstatus/todoagenda#85]
I'm using Etar Agenda, and I like to have a monthly view by default. But the only way I open the app is when I click on the Todoagenda plugin. So I would love to have the plugin open the app on the view I chose in my calendar app settings : the monthly view. Maybe keep the opening on daily view when we click on a specific date on the plugin ?

Thanks by advance.

**Comment by yvolk** [comment]
@Kalytis Do you mean that you use this app with our "ToDo Agenda" widget: https://play.google.com/store/apps/details?id=ws.xsoh.etar ?

**Comment by Kalytis** [comment]
Yes, exactly.

**Comment by yvolk** [comment]
Hello @Kalytis.
When you click on the widget, it generates some "Calendar app independent" _intent_ that may be intercepted by any "Calendar" app.
And I don't know about any way to change that intent, so that it points to any particular view... There may be something for "Etar Agenda", but that won't work for other Calendar apps, I think...

So looks like the best way to change that default view is inside that Calendar app.

**Comment by Kalytis** [comment]
Hi (again) @yvolk, I've already set the default view in Etar as "monthly view", but when Etar is opened through clicking on my ToDo widget, it doesn't seem to work... it only works when I open the app directly with the icon (or when I click on their own widget, I guess).

**Comment by yvolk** [comment]
@Kalytis I looked up code https://github.com/andstatus/todoagenda/blob/2c83fae82a62b74e0db84cef697657a401173c4e/app/src/main/kotlin/org/andstatus/todoagenda/util/CalendarIntentUtil.kt#L12 and see that the intent to open a Calendar app id simply "content://com.android.calendar/time/" with milliseconds appended. Nothing more. 
According to the Android documentation https://developer.android.com/guide/topics/providers/calendar-provider.html#intents
this is THE ONLY intent to open calendar. It says: "Open calendar to the time specified by <ms_since_epoch>."
Moreover, on my Android 14 device Google Calendar opens at Month view.

For me above information confirms that this is Etar app team that needs to allow a User to customize a Calendar view that is opened on the intent.
