### ISSUE TITLE
Editing an event adds the "Participate ?" operand, and not ticking "Yes" sets the event as Unconfirmed

### ISSUE THREAD

**Issue by Kalytis** [andstatus/todoagenda#86]
I tried to make the title as indicative as possible. When I create an event on Mozilla Thunderbird Lightning, then edit it on ToDo Agenda, it adds a question that asks me to confirm my participation to this event. I never use this on any of my clients, and I don't have the utility of it, so I never tick it.

But then, not ticking it sets the status of the event as Unconfirmed, which messes up a lot of things on the displays of my events.

Thanks by advance !

**Comment by yvolk** [comment]
@Kalytis When you edit an event "on ToDo Agenda" you actually edit it in some calendar apps of your device that is chosen as default for the action... 
Maybe you simply need to change that default app to your favorite one (e.g. to "Mozilla Thunderbird Lightning" if it has Android version?)

ToDo Agenda cannot add or edit events. It makes a corresponding call ("intent") to a Device, and Android System decides, which app should be actually called.

**Comment by Kalytis** [comment]
Oh I'm so sorry, I got mixed up with the Github repo to post this in...

Really sorry for the inconvenience !
