### ISSUE TITLE
Provide a way to show the phrase "# days" remaining when formatting a date

### ISSUE THREAD

**Issue by drcouzelis** [andstatus/todoagenda#87]
Todo Agenda provides a way to show the number of days remaining. Unfortunately, there is no way to display the following formatted date string in the list of events.

- Event, Today
- Event, Tomorrow
- Event, in 3 days
- Event, in 4 days

This is because if I add the text "in bbbbb days" it will display "in Today days". Please consider adding a way to format the date string as specified above.

Thank you for making Todo Agenda. :)

**Comment by yvolk** [comment]
@drcouzelis Please look here: https://github.com/andstatus/todoagenda/issues/7
"BBBB" is what you need?!

**Comment by drcouzelis** [comment]
Haha Yes, that is perfect! I apologize for missing it. Thank you!
