### ISSUE TITLE
[Feature Request] Add "Add Task" Button

### ISSUE THREAD

**Issue by drdanz** [andstatus/todoagenda#9]
At the moment it is possible to add a new event, but, even though tasks from OpenTasks are shown, there is no way to add a new task.

**Comment by drdanz** [comment]
By the way, thank you a lot for this widget, It's incredibly useful.
[#ilovefs](https://fsfe.org/campaigns/ilovefs/)

**Comment by yvolk** [comment]
@drdanz As a first though, I would suggest for you to look for existence of something like "Add task" button (small widget) in the Tasks app
?!

**Comment by yvolk** [comment]
Any suggestion for an icon of this button (different from "Add new calendar event" button)? As I see Material design has "Add task" icon: https://material.io/resources/icons/?search=task&icon=task&style=baseline

**Comment by yvolk** [comment]
Implemented in v.4.2.0 #3

**Comment by yvolk** [comment]
As I see, currently the "Add task button doesn't work for "Tasks of Samsung Calendar" app. 

I don't know the correct command ("Intent" in terms of Android) to tell the app that I want to add a new task.
See lines 30 - 32 here:
https://github.com/andstatus/todoagenda/blob/master/app/src/main/java/org/andstatus/todoagenda/task/samsung/SamsungTasksProvider.java

But maybe @ekalin or somebody else could help me here?!
