### ISSUE TITLE
Can't find tasks after upgrade

### ISSUE THREAD

**Issue by YJRXFwZ** [andstatus/todoagenda#93]
I just installed version 4.5.3. All of my task lists are now "not found".  I have uninstalled and re-installed the app and restarted the phone. I verified the permissions and Tasks has been granted them in Todo Agenda. New widgets don't see any task lists. 

Phone: pixel 4a android v 12 
Tasks.org v12. 5

{
  "deviceInfo": {
    "versionCode": 31,
    "versionRelease": "12",
    "versionCodename": "REL",
    "buildManufacturer": "Google",
    "buildBrand": "google",
    "buildModel": "Pixel 4a"
  },
  "applicationInfo": {
    "versionName": "4.5.3",
    "versionCode": 695
  },
  "settings": {
    "widgetId": 57,
    "widgetHeaderDateFormat": "defaultYtt:",
    "widgetInstanceName": "Todo Agenda 34",
    "activeSources": [
      {
        "providerType": 1,
        "id": 3,
        "title": "Holidays in United States",
        "summary": "xxxxxxxxxxx@gmail.com",
        "color": -12396910,
        "isAvailable": true
      }
    ],
    "eventRange": 30,
    "eventsEnded": "NONE",
    "fillAllDay": true,
    "hideBasedOnKeywords": "",
    "widgetHeaderBackgroundColor": -1056369829,
    "pastEventsBackgroundColor": -1018494203,
    "todaysEventsBackgroundColor": -1020456373,
    "backgroundColor": -1526726656,
    "textColorSource": "shading",
    "headerTheme": "BLACK",
    "widgetHeaderTextColor": -1694498817,
    "dayHeaderThemePast": "BLACK",
    "dayHeaderTextColorPast": -3355444,
    "entryThemePast": "BLACK",
    "eventTextColorPast": -1,
    "dayHeaderTheme": "BLACK",
    "dayHeaderTextColorToday": -8947849,
    "entryTheme": "BLACK",
    "eventTextColorToday": -16777216,
    "dayHeaderThemeFuture": "DARK",
    "dayHeaderTextColorFuture": -3355444,
    "entryThemeFuture": "DARK",
    "eventTextColorFuture": -1,
    "showDaysWithoutEvents": false,
    "showDayHeaders": true,
    "dayHeaderDateFormat": "defaultWeekday:",
    "horizontalLineBelowDayHeader": false,
    "showPastEventsUnderOneHeader": true,
    "showPastEventsWithDefaultColor": false,
    "showEventIcon": true,
    "entryDateFormat": "hidden:",
    "showEndTime": true,
    "showLocation": true,
    "dateFormat": "auto",
    "lockedTimeZoneId": "",
    "snapshotMode": "live_data",
    "refreshPeriodMinutes": 10,
    "eventEntryLayout": "DEFAULT",
    "multiline_title": false,
    "multiline_details": true,
    "showOnlyClosestInstanceOfRecurringEvent": false,
    "hideDuplicates": false,
    "allDayEventsPlacement": "top_day",
    "taskScheduling": "date_due",
    "taskWithoutDates": "end_of_list",
    "filterMode": "normal",
    "indicateAlerts": false,
    "indicateRecurring": false,
    "compactLayout": true,
    "widgetHeaderLayout": "ONE_ROW",
    "textSizeScale": "0.8",
    "dayHeaderAlignment": "RIGHT"
  },
  "resultsVersion": 3,
  "results": [
    {
      "providerType": 1,
      "executedAt": 1647295099896,
      "timeZoneId": "America\/Denver",
      "millisOffsetUtcToLocal": -21600000,
      "standardMillisOffsetUtcToLocal": -25200000,
      "uri": "content:\/\/com.android.calendar\/instances\/when\/1647125899896\/1649887099896",
      "projection": [
        "calendar_id",
        "event_id",
        "eventStatus",
        "title",
        "begin",
        "end",
        "allDay",
        "eventLocation",
        "hasAlarm",
        "rrule",
        "displayColor",
        "calendar_color"
      ],
      "selection": "selfAttendeeStatus!=2 AND (calendar_id = 3 )",
      "selectionArgs": [],
      "sortOrder": "startDay ASC, allDay DESC, begin ASC ",
      "rows": [
        {
          "allDay": {
            "type": 1,
            "value": 1
          },
          "event_id": {
            "type": 1,
            "value": 1000
          },
          "calendar_id": {
            "type": 1,
            "value": 3
          },
          "eventLocation": {
            "type": 3,
            "value": ""
          },
          "eventStatus": {
            "type": 1,
            "value": 1
          },
          "end": {
            "type": 1,
            "value": 1647216000000
          },
          "displayColor": {
            "type": 1,
            "value": -12396910
          },
          "title": {
            "type": 3,
            "value": "Daylight Saving Time starts"
          },
          "begin": {
            "type": 1,
            "value": 1647129600000
          },
          "hasAlarm": {
            "type": 1,
            "value": 0
          },
          "calendar_color": {
            "type": 1,
            "value": -12396910
          }
        },
        {
          "allDay": {
            "type": 1,
            "value": 1
          },
          "event_id": {
            "type": 1,
            "value": 1050
          },
          "calendar_id": {
            "type": 1,
            "value": 3
          },
          "eventLocation": {
            "type": 3,
            "value": ""
          },
          "eventStatus": {
            "type": 1,
            "value": 1
          },
          "end": {
            "type": 1,
            "value": 1647561600000
          },
          "displayColor": {
            "type": 1,
            "value": -12396910
          },
          "title": {
            "type": 3,
            "value": "St. Patrick's Day"
          },
          "begin": {
            "type": 1,
            "value": 1647475200000
          },
          "hasAlarm": {
            "type": 1,
            "value": 0
          },
          "calendar_color": {
            "type": 1,
            "value": -12396910
          }
        }
      ]
    }
  ]
}

**Comment by yvolk** [comment]
@YJRXFwZ Thank you for reporting.
I just checked and I do see tasks list and tasks on a widget on my old Android 7 tablet, but Task lists really disappeared on Android 12. Will investigate this.

**Comment by landstander668** [comment]
One thing I noticed is that Tasks.org released version 2.5 fairly recently. It's listed as 27 February on their [changelog](https://github.com/tasks/tasks/blob/main/CHANGELOG.md), and appears to have arrived on Google Play on 8 March. I **believe** tasks were still visible in Todo after installing that update but am not 100% certain, so it might be possible that their communication was inadvertently broken on the Tasks.org side.

Tasks were definitely showing normally on my Android 12 device (Pixel 5) until very recently, however.

**Comment by yvolk** [comment]
Currently I have tasks.org app v.12.6 and ToDo Agenda v.4.5.4 on both my devices:
1. Android 7.1 sees tasks
2. Android 12 doesn't see tasks.
The problem appeared, as I think, after I changed compatibility level of ToDo Agenda to API 31, i.e. to Android 12, so some new rules are now being applied to ToDo Agenda on Android 12 devices.

My first check on Android 12 showed that ToDo Agenda simply cannot detect presence of the Tasks.org app, and this is why it neither asks for permission to access its tasks, nor shows its tasks in the widget.
(BTW, at the same time nothing changed for "Calendar provider"...)
I will look deeper into the tasks.org app's Source code to understand, why is this.

**Comment by yvolk** [comment]
As expected, the problem was in Android security tightening: ToDo Agenda was not allowed to see Tasks apps by default (see
https://developer.android.com/training/package-visibility and https://developer.android.com/training/package-visibility/declaring).

I explicitly declared the tasks apps' "authorities", and the tasks lists and tasks re-appeared.
Please check #3

**Comment by landstander668** [comment]
I just updated to v4.5.5 via the beta process, and tasks have reappeared for me as well. Thanx!

**Comment by YJRXFwZ** [comment]
It is working now and I am able to see all of my tasks again.  Thank you!
