### ISSUE TITLE
All Tasks and Calendar Events from some calendars show grey after update to ToDoAgenda 4.5.3

### ISSUE THREAD

**Issue by jimfum** [andstatus/todoagenda#94]
Calendar events are correctly in white text color as before but Task.org events are in grey. Cannot find settings that would allow me to control that. Was fine (all white) before 4.5.3.

**Comment by yvolk** [comment]
Hi @jimfum , I think this change is caused by "Implement strikethrough and partial transparency for event status", please see https://github.com/andstatus/todoagenda/pull/82 
Please try to change status... in that events.

**Comment by jimfum** [comment]
Hi @yvolk. I've checked the refered ticket but don't see what I could do. You're suggesting it's because the event is tentative, right? That confuses me, because the tasks are just for me and I don't see anything about making them 'accepted' automatically.

**Comment by yvolk** [comment]
@feilen Could you help with the issue in your change, please.
...Anyway, looks like we will need a new setting to disable this "strikethrough and partial transparency for event status" feature...

**Comment by JanHellwig** [comment]
Hi.
I've run into the same issue as @jimfum on some of my calendars. It seems to indeed be related to the status of the events, but I can't even find an option to change that in my calendar app.

Having an option to either disable the transparency for status would be much appreciated as the widget currently looks pretty broken for me. Alternatively it might also be an idea to just expose the color for tentative events in the settings in the same way you can configure past events to have a different color that future ones?

**Comment by yvolk** [comment]
> I've run into the same issue as @jimfum on some of my calendars.

@JanHellwig It's interesting, what is special in those calendars, how do think?
And could you send me (or post here) some (filtered out for privacy or created specifically for testing) "Share events and settings for debugging" as described in https://github.com/andstatus/todoagenda/issues/71 in order for me to understand, why some events are interpreted as tentative, and some are not.

**Comment by zelleb** [comment]
I sync my calendars with my nextcloud. The automatically created contact birthdays calendar events are all greyed out. They are created with a reminder at midnight. Hope that helps.

**Comment by pbarbiero** [comment]
I have the same issue -- any events now (from exchange) that in my google calendar have the 'outline' instead of the solid fill, show faded in the todo agenda and I have no option to change this back to how it was before.

**Comment by yvolk** [comment]
@pbarbiero Could you send me (or post here) some (filtered out for privacy or created specifically for testing) "Share events and settings for debugging" as described in https://github.com/andstatus/todoagenda/issues/71 so I could see actual data that our widget receives.

**Comment by yvolk** [comment]
Thank you all!
Turning all tasks grey was really a bug that I didn't notice.
As a quick fix I also disabled the "transparency for tentative tasks" feature. If needed, we will add it as a separate color setting as suggested above.
Please test v.4.5.4 here #3

Thank you, @feilen, please check my fix.

**Comment by feilen** [comment]
You're quick! And yeah that should be plenty.

I might look into the per-calendar approach first then... Usefulness is questionable if you end up with even just one calendar thats got garbage data, one way or another.

**Comment by yvolk** [comment]
I published the fixed v.4.5.4 for F-Droid and to Google Play. It's also available immediately here: #3

**Comment by yvolk** [comment]
> You're quick!

@feilen That's because I got several emails in addition to post here. And realized that the problem affect many users.
BTW, according to Google Play there are more than 10 thousand of ToDo Agenda's users who updated their apps in Google Play recently. Probably even more in F-Droid.
