### ISSUE TITLE
Colors not being consistent after updating to 4.5.3 version

### ISSUE THREAD

**Issue by miquecg** [andstatus/todoagenda#96]
So I have same settings for today and future events: transparent background and white color for headers and text.

Most future events appear dimmed, with gray color in descriptions instead of white. I tried recreating the widget once again and switching between automatic, manual and custom colors but issue persists.

What is strange is that tomorrow event and another on next week have correct colors. I have no events today in calendar so tomorrow one is first on the list.

**Comment by yvolk** [comment]
Hi @miquecg. This was reported in #94 and fixed in v.4.5.4
Available e.g. here: #3 (4.5.5. already there...)

**Comment by miquecg** [comment]
Ah, sorry. I searched for "colors" but didn't get anything.

Thanks for the quick fix :tada:
