### ISSUE TITLE
Any tasks of Tasks app not shown in To-Do Agenda anymore, starting with version 4.53

### ISSUE THREAD

**Issue by just-Nob** [andstatus/todoagenda#97]
Starting with version 4.5.x (i.e. currently v. 4.5.3 & 4.5.4), no tasks is shown anymore. Going back to 4.4.0 solves the issue, all tasks are shown again.
The problem seems to be that To-Do Agenda isn't able to see any of Tasks' lists. When opening the dialog where to choose with calendars & tasks to show, the tasks areshown as "can not be found" (or something similar).

This seems to be very similar to #66, with the difference that it doesn't matter if the Tasks app is open or not, but depends of To-Do Agenda's version.

**Comment by yvolk** [comment]
Hi @just-Nob The problem was found and fixed in 4.5.5, see https://github.com/andstatus/todoagenda/issues/93

**Comment by just-Nob** [comment]
Oh, sorry. Thanks for your hint!
Seems I was blind Ehen searching for this....
